Repository SwanHubX/SwanLab, pull requests merged in 2023-12, with the labels that each got.

#65 update reamde
  README.md
  README_zh-hans.md
Labels: documentation

#66 Feat/readme
  README.md
  README_zh-hans.md
Labels: documentation

#46 v0.1.0
  .github/ISSUE_TEMPLATE/ask for question.md
  .github/workflows/publish-to-pypi.yml
  .vscode/launch.json
  build_pypi.py
  package.json
  pyproject.toml
  swanlab/__init__.py
  swanlab/database/__init__.py
  swanlab/database/experiments_name.py
  swanlab/database/expriment.py
  swanlab/database/main.py
  swanlab/database/project.py
  swanlab/database/table.py
  swanlab/database/utils.py
  swanlab/log/console.py
  swanlab/log/log.py
  swanlab/package.json
  swanlab/server/api/experiment.py
  swanlab/server/router.py
  swanlab/utils/__init__.py
  swanlab/utils/font.py
  swanlab/utils/package.py
  test/create_experiment.py
  test/test_logging/app.py
  vite.config.js
  vue/.env
  vue/.env.mock
  vue/src/App.vue
  vue/src/api/http.js
  vue/src/assets/font/JetBrainsMono-Regular.ttf
  vue/src/components/HomeSiderBar.vue
  vue/src/i18n/en-US/common.json
  vue/src/i18n/en-US/error.json
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/en-US/home.json
  vue/src/i18n/en-US/index.js
  vue/src/i18n/en-US/moment.json
  vue/src/i18n/en-US/sider.json
  vue/src/i18n/index.js
  vue/src/i18n/zh-CN/experiment.json
  vue/src/layouts/ExperimentLayout.vue
  vue/src/router/index.js
  vue/src/style.scss
  vue/src/utils/time.js
  vue/src/views/experiment/ExperimentView.vue
  vue/src/views/experiment/components/TabsHeader.vue
  vue/src/views/experiment/pages/LogPage.vue
  vue/src/views/experiment/pages/chart/ChartPage.vue
  vue/src/views/experiment/pages/chart/components/EmptyExperiment.vue
  vue/src/views/experiment/pages/chart/components/G2Chart.vue
  vue/src/views/experiment/pages/log/LogPage.vue
  vue/src/views/home/HomeView.vue
Labels: enhancement

#72 Bugfix/time
  vue/src/utils/time.js
Labels: bug, good attempt

#73 fix broken link in readme
  README_zh-hans.md
Labels: bug, documentation, good attempt

#74 Feat/update readme
  .eslintignore
  .prettierignore
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  README_zh-hans.md
  readme_files/swanlab-logo-dark.svg
  readme_files/swanlab-logo-light.svg
Labels: documentation

#83 Refactor/table
  swanlab/server/api/experiment.py
  vue/src/components/SLTable.vue
  vue/src/views/experiment/pages/index/components/ExperimentConfig.vue
  vue/src/views/home/HomeView.vue
  vue/src/views/home/components/ExperimentName.vue
Labels: enhancement

#84 Feature/project summaries
  swanlab/server/api/project.py
  vue/src/views/home/HomeView.vue
Labels: enhancement

#85 Fixbug/table
  vue/src/components/SLTable.vue
  vue/src/i18n/en-US/common.json
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/zh-CN/common.json
  vue/src/views/experiment/pages/index/components/ExperimentConfig.vue
  vue/src/views/home/HomeView.vue
Labels: bug

#87 UI/table
  vue/src/components/SLTable.vue
  vue/src/views/home/HomeView.vue
Labels: enhancement, UI/UX Enhancement

#89 Feature/expr info
  swanlab/database/system.py
  vue/src/components/HomeSiderBar.vue
  vue/src/components/SLTable.vue
  vue/src/i18n/en-US/experiment.json
  vue/src/views/experiment/pages/index/components/ExperimentConfig.vue
  vue/src/views/experiment/pages/index/components/ExperimentHeader.vue
  vue/src/views/home/HomeView.vue
Labels: enhancement

#90 UI/table hover
  requirements.txt
  vue/src/components/SLTable.vue
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/en-US/home.json
  vue/src/i18n/en-US/moment.json
  vue/src/views/experiment/pages/index/components/ExperimentConfig.vue
Labels: UI/UX Enhancement

#78 refactor/chart
  .prettierignore
  .vscode/settings.json
  swanlab/database/__init__.py
  swanlab/database/chart.py
  swanlab/database/expriment.py
  swanlab/database/main.py
  swanlab/database/system.py
  swanlab/database/table.py
  swanlab/server/api/experiment.py
  test/create_experiment.py
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/zh-CN/experiment.json
  vue/src/views/experiment/pages/chart/ChartPage.vue
  vue/src/views/experiment/pages/chart/components/ChartContainer.vue
  vue/src/views/experiment/pages/chart/components/G2Chart.vue
  vue/src/views/experiment/pages/chart/components/package/LineChart.vue
  vue/src/views/experiment/pages/chart/components/package/README.md
  vue/src/views/experiment/pages/chart/components/package/utils.js
  vue/src/views/experiment/pages/index/components/ExperimentHeader.vue
Labels: bug, good attempt

#93 fix #91
  vue/src/api/http.js
  vue/src/views/experiment/pages/chart/ChartPage.vue
Labels: bug

#94 fix #92
  swanlab/server/api/experiment.py
  swanlab/server/api/project.py
  vue/src/store/modules/experiment.js
  vue/src/views/experiment/ExperimentView.vue
  vue/src/views/experiment/pages/chart/ChartPage.vue
  vue/src/views/experiment/pages/chart/components/package/LineChart.vue
Labels: bug, enhancement, UI/UX Enhancement

#104 Fixbug/type check
  .vscode/swanlab.code-snippets
  swanlab/__init__.py
  swanlab/database/__init__.py
  swanlab/database/chart.py
  swanlab/database/experiment.py
  swanlab/database/main.py
  swanlab/database/modules/__init__.py
  swanlab/database/modules/base.py
  swanlab/database/modules/chart.py
  swanlab/database/project.py
  swanlab/database/table.py
  swanlab/env.py
  swanlab/server/api/experiment.py
  swanlab/server/api/project.py
  swanlab/utils/file.py
  test/create_experiment.py
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/zh-CN/experiment.json
  vue/src/store/modules/project.js
  vue/src/views/experiment/ExperimentView.vue
  vue/src/views/experiment/pages/chart/ChartPage.vue
  vue/src/views/experiment/pages/chart/components/ChartContainer.vue
  vue/src/views/experiment/pages/chart/components/package/LineChart.vue
  vue/src/views/experiment/pages/chart/components/package/README.md
  vue/src/views/experiment/pages/chart/components/package/UnknownChart.vue
  vue/src/views/experiment/pages/chart/components/package/utils.js
Labels: bug, enhancement

#108 feat: stop experiment on dashboard
  swanlab/server/api/experiment.py
  vue/src/components/SLStatusLabel.vue
  vue/src/i18n/en-US/experiment.json
  vue/src/store/modules/experiment.js
  vue/src/views/experiment/pages/index/components/ExperimentHeader.vue
  vue/src/views/experiment/pages/index/components/StopButton.vue
Labels: enhancement

#118 Fixbug/table
  swanlab/server/api/project.py
  vue/src/views/experiment/pages/index/components/ExperimentHeader.vue
Labels: bug
