Repository SwanHubX/SwanLab, pull requests merged in 2024-10, with the labels that each got.

#716 update:requiremnents
  requirements.txt
Labels: 💪 enhancement

#720 docs: update readme
  README.md
  README_EN.md
  README_cn.md
Labels: 📚 documentation

#723 force choice version
  requirements.txt
Labels: 🐛 bug

#724 docs: readme more language
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation
