Repository SwanHubX/SwanLab, pull requests merged in 2024-12, with the labels that each got.

#745 feat: integration xgboost
  swanlab/integration/xgboost.py
  test/integration/xgboost/train_xgboost.py
Labels: 💪 enhancement

#746 feat: integration lightgbm
  swanlab/integration/lightgbm.py
  test/integration/lightgbm/train_lightgbm.py
Labels: 💪 enhancement

#728 实现硬件监控基础数据采集
  requirements.txt
  swanlab/data/callback_cloud.py
  swanlab/data/cloud/start_thread.py
  swanlab/data/cloud/sysmetrics_collector.py
  swanlab/data/run/exp.py
  swanlab/data/run/main.py
Labels: 💪 enhancement, good first issue

#749 refactor: hardware task and model
  docs/实验元数据.md
  docs/硬件信息采集.md
  swanlab/data/callback_cloud.py
  swanlab/data/callback_local.py
  swanlab/data/formater.py
  swanlab/data/run/helper.py
  swanlab/data/run/main.py
  swanlab/data/run/metadata/__init__.py
  swanlab/data/run/metadata/cooperation/__init__.py
  swanlab/data/run/metadata/hardware/soc/apple.py
  swanlab/data/run/webhook.py
  test/unit/data/run/test_helper.py
Labels: 💪 enhancement

#750 feat: increase log len
  docs/硬件信息采集.md
  requirements.txt
  swanlab/data/run/main.py
  swanlab/log/console.py
  test/unit/log/test_log.py
Labels: 💪 enhancement

#751 feat: hardware monitor
  docs/硬件信息采集.md
  requirements.txt
  swanlab/api/upload/model.py
  swanlab/data/callback_cloud.py
  swanlab/data/run/exp.py
  swanlab/data/run/helper.py
  swanlab/data/run/main.py
  swanlab/data/run/metadata/__init__.py
  swanlab/data/run/metadata/hardware/__init__.py
  swanlab/data/run/metadata/hardware/cpu.py
  swanlab/data/run/metadata/hardware/gpu/nvidia.py
  swanlab/data/run/metadata/hardware/memory.py
  swanlab/data/run/metadata/hardware/npu/ascend.py
  swanlab/data/run/metadata/hardware/soc/apple.py
  swanlab/data/run/metadata/hardware/type.py
  swanlab/data/run/metadata/hardware/utils.py
  test/unit/data/run/metadata/hardware/gpu/test_nvidia.py
  test/unit/data/run/metadata/hardware/soc/test_apple.py
  test/unit/data/run/metadata/hardware/test_type.py
  test/unit/data/run/metadata/hardware/test_utils.py
  test/unit/data/run/metadata/test_utils.py
Labels: 💪 enhancement

#754 chore: fix some misc
  swanlab/data/run/metadata/hardware/gpu/nvidia.py
  swanlab/data/run/metadata/hardware/type.py
Labels: 🐛 bug

#757 docs: changelog more lang
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation
