Repository SwanHubX/SwanLab, pull requests merged in 2024-11, with the labels that each got.

#730 feat-integration-keras
  swanlab/integration/keras.py
  test/integration/keras/keras_train.py
Labels: 💪 enhancement

#732 replace settings to public
  swanlab/data/run/main.py
  swanlab/data/run/public.py
  test/unit/data/test_sdk.py
Labels: 💪 enhancement

#735 docs: update README
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation

#740 feat/webhook
  requirements.txt
  swanlab/data/callback_local.py
  swanlab/data/run/helper.py
  swanlab/data/run/main.py
  swanlab/data/run/metadata/__init__.py
  swanlab/data/run/metadata/coop/qing_cloud.py
  swanlab/data/run/metadata/cooperation.py
  swanlab/data/run/metadata/hardware.py
  swanlab/data/run/metadata/requirements.py
  swanlab/data/run/metadata/runtime.py
  swanlab/data/run/namer.py
  swanlab/data/run/system/__init__.py
  swanlab/data/run/system/bin/apple_gpu_stats
  swanlab/data/run/system/info.py
  swanlab/data/run/system/monitor.py
  swanlab/data/run/webhook.py
  swanlab/env.py
Labels: 🐛 bug, 💪 enhancement

#741 feat: ascend npu detection
  swanlab/data/run/metadata/hardware.py
  swanlab/data/run/metadata/utils/ascend.py
Labels: 💪 enhancement
