Repository SwanHubX/SwanLab, pull requests merged in 2024-06, with the labels that each got.

#604 集成了huggingface accelerate
  swanlab/integration/accelerate.py
  test/integration/accelerate/accelerate_train.py
  test/integration/accelerate/requirements.txt
Labels: 💪 enhancement

#603 refactor data
  requirements.txt
  swanlab/api/cos.py
  swanlab/api/http.py
  swanlab/api/upload/__init__.py
  swanlab/api/upload/model.py
  swanlab/cloud/log_collector.py
  swanlab/cloud/start_thread.py
  swanlab/data/__init__.py
  swanlab/data/callback_cloud.py
  swanlab/data/callback_local.py
  swanlab/data/modules/__init__.py
  swanlab/data/modules/_utils.py
  swanlab/data/modules/audio.py
  swanlab/data/modules/audio/__init__.py
  swanlab/data/modules/base.py
  swanlab/data/modules/chart.py
  swanlab/data/modules/image.py
  swanlab/data/modules/image/__init__.py
  swanlab/data/modules/image/bounding_boxes.py
  swanlab/data/modules/image/image_mask.py
  swanlab/data/modules/line/__init__.py
  swanlab/data/modules/object_3d.py
  swanlab/data/modules/text.py
  swanlab/data/modules/text/__init__.py
  swanlab/data/modules/utils_modules/__init__.py
  swanlab/data/modules/video.py
  swanlab/data/modules/wrapper.py
  swanlab/data/run/callback.py
  swanlab/data/run/exp.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
  swanlab/data/settings.py
  swanlab/db/callback.py
  swanlab/error.py
  swanlab/server/controller/experiment.py
  swanlab/utils/file.py
  test/unit/api/pytest_http.py
  test/unit/data/modules/audio/pytest_audio.py
  test/unit/data/modules/image/pytest_image.py
  test/unit/data/modules/line/pytest_line.py
  test/unit/data/modules/pytest_base.py
  test/unit/data/modules/pytest_wrapper.py
  test/unit/data/modules/text/pytest_text.py
  test/unit/data/pytest_sdk.py
  test/unit/data/run/pytest_main.py
  test/unit/data/run/test_exp.py
  test/unit/utils/pytest_file.py
Labels: 🐛 bug, 💪 enhancement

#607 opt config
  swanlab/api/upload/__init__.py
  swanlab/data/callback_cloud.py
  swanlab/data/run/callback/models/runtime.py
  swanlab/data/run/callback/utils.py
  swanlab/data/run/config.py
  swanlab/data/run/main.py
  swanlab/data/run/operator.py
  test/unit/data/run/pytest_config.py
Labels: 🐛 bug, 💪 enhancement

#612 update encoding="utf-8"
  README.md
  README_cn.md
  readme_files/overview-2.png
  swanlab/data/callback_local.py
  swanlab/package.json
  swanlab/package.py
Labels: 🐛 bug

#613 fix create
  swanlab/api/upload/__init__.py
  swanlab/api/upload/model.py
  test/unit/api/upload/test_model.py
Labels: 🐛 bug

#615 Feat/Env add PID and verbose Python version
  swanlab/data/run/system/info.py
Labels: 💪 enhancement

#625 Update integration accelerate
  swanlab/integration/accelerate.py
Labels: 🐛 bug, 💪 enhancement

#628 修复了mmengine集成中SwanlabVisBackend的save_dir不能为None的问题
  swanlab/integration/mmengine.py
  test/integration/mmengine/README.md
  test/integration/mmengine/mmengine_train.py
  test/integration/mmengine/mmengine_visualizer_import.py
  test/integration/mmengine/requirements.txt
Labels: 🐛 bug

#629 use swankit and fix #627
  requirements.txt
  swanlab/cli/commands/dashboard/watch.py
  swanlab/data/run/main.py
  swanlab/log/console.py
  swanlab/log/log.py
  swanlab/package.json
  test/unit/log/pytest_log.py
Labels: 🐛 bug, good attempt

#630 update toolkit
  requirements.txt
  swanlab/log/console.py
  test/unit/log/pytest_log.py
Labels: 🐛 bug

#633 change dependence
  pyproject.toml
  requirements-meida.txt
  requirements.txt
  swanlab/data/formater.py
  swanlab/data/modules/audio/__init__.py
  swanlab/data/modules/image/__init__.py
  swanlab/data/modules/wrapper.py
  swanlab/data/run/system/info.py
Labels: 💪 enhancement

#636 fix sharding and encoding
  requirements-dev.txt
  swanlab/log/console.py
  test/unit/log/pytest_log.py
  tutils/__init__.py
  tutils/check.py
Labels: 🐛 bug

#635 fix import
  swanlab/data/modules/audio/__init__.py
  swanlab/data/modules/image/__init__.py
Labels: 🐛 bug
