Repository SwanHubX/SwanLab, pull requests merged in 2024-02, with the labels that each got.

#296 Feature/audio analysis
  requirements.txt
  swanlab/__init__.py
  swanlab/data/__init__.py
  swanlab/data/modules/__init__.py
  swanlab/data/modules/audio.py
  swanlab/data/modules/base.py
  swanlab/data/modules/chart.py
  swanlab/data/modules/image.py
  swanlab/data/run/exp.py
  swanlab/data/settings.py
  swanlab/server/app.py
  swanlab/server/router/media.py
  swanlab/server/settings.py
  test/create_experiment.py
  test/db/test_chart.py
  vue/src/assets/iconfont.js
  vue/src/charts/components/ChartContainer.vue
  vue/src/charts/components/DownloadButton.vue
  vue/src/charts/components/PlayButton.vue
  vue/src/charts/components/SlideBar.vue
  vue/src/charts/modules/AudioModule.vue
  vue/src/charts/modules/README.md
  vue/src/charts/package/AudioChart.vue
  vue/src/charts/package/LineChart.vue
  vue/src/charts/package/utils.js
  vue/src/components/SLSlideBar.vue
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/zh-CN/experiment.json
  vue/src/views/experiment/pages/chart/ChartPage.vue
Labels: enhancement

#294 fix: time format
  swanlab/log/console.py
  swanlab/server/controller/experiment.py
  test/_server.py
  vue/src/layouts/ExperimentLayout.vue
  vue/src/views/experiment/pages/log/LogPage.vue
  vue/src/views/home/HomeView.vue
Labels: bug

#315 refactor: log dir
  vue/src/i18n/en-US/home.json
  vue/src/i18n/zh-CN/home.json
  vue/src/store/modules/experiment.js
  vue/src/utils/time.js
  vue/src/views/experiment/pages/environment/pages/EnvIndex.vue
  vue/src/views/home/HomeView.vue
Labels: enhancement

#314 Feat/image chart
  .vscode/swanlab.code-snippets
  swanlab/data/modules/audio.py
  swanlab/data/modules/base.py
  swanlab/data/modules/chart.py
  swanlab/data/modules/image.py
  swanlab/data/modules/text.py
  swanlab/data/run/exp.py
  swanlab/data/run/main.py
  swanlab/data/utils/file.py
  test/create_experiment.py
  vue/src/charts/components/ChartContainer.vue
  vue/src/charts/components/DownloadButton.vue
  vue/src/charts/modules/AudioModule.vue
  vue/src/charts/package/AudioChart.vue
  vue/src/charts/package/ImageChart.vue
  vue/src/charts/package/LineChart.vue
  vue/src/charts/package/UnknownChart.vue
  vue/src/i18n/en-US/common.json
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/zh-CN/common.json
  vue/src/i18n/zh-CN/experiment.json
  vue/src/views/experiment/pages/chart/ChartPage.vue
Labels: enhancement

#316 fix step bug
  vue/src/charts/package/LineChart.vue
Labels: bug

#313 Feature/get charts
  .gitignore
  swanlab/db/__init__.py
  swanlab/db/db_connect.py
  swanlab/db/error.py
  swanlab/db/model.py
  swanlab/db/models/charts.py
  swanlab/db/models/displays.py
  swanlab/db/models/experiments.py
  swanlab/db/models/namespaces.py
  swanlab/db/models/projects.py
  swanlab/db/models/sources.py
  swanlab/db/models/tags.py
  swanlab/db/table_config.py
  swanlab/db/utils/__init__.py
  swanlab/db/utils/chart.py
  swanlab/server/controller/experiment.py
  swanlab/server/controller/project.py
  swanlab/server/router/project.py
  unit/utils/add_multi_exp_chart.py
  unit/utils/multi_exp_chart.py
Labels: enhancement

#319 Feat/multiple experiment chart
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  swanlab/data/run/db.py
  swanlab/data/run/exp.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
  swanlab/db/__init__.py
  swanlab/db/db_connect.py
  swanlab/db/error.py
  swanlab/db/model.py
  swanlab/db/models/charts.py
  swanlab/db/models/displays.py
  swanlab/db/models/experiments.py
  swanlab/db/models/namespaces.py
  swanlab/db/models/projects.py
  swanlab/db/models/sources.py
  swanlab/db/models/tags.py
  swanlab/db/table_config.py
  swanlab/db/utils/__init__.py
  swanlab/db/utils/chart.py
  swanlab/log/console.py
  swanlab/package.json
  swanlab/server/controller/experiment.py
  swanlab/server/controller/project.py
  swanlab/server/router/experiment.py
  swanlab/server/router/project.py
  test/create_experiment.py
  unit/main.py
  unit/utils/add_multi_exp_chart.py
  unit/utils/create_exp.py
  unit/utils/multi_exp_chart.py
  unit/utils/package.py
  vue/src/assets/iconfont.js
  vue/src/charts/components/ChartContainer.vue
  vue/src/charts/package/AudioChart.vue
  vue/src/charts/package/ImageChart.vue
  vue/src/charts/package/LineChart.vue
  vue/src/i18n/en-US/experiment.json
  vue/src/layouts/ExperimentLayout.vue
  vue/src/layouts/main/components/SideBar.vue
  vue/src/store/modules/project.js
  vue/src/views/charts/ChartsView.vue
  vue/src/views/charts/components/ChartsPage.vue
  vue/src/views/experiment/pages/chart/ChartPage.vue
Labels: bug, enhancement

#321 fix: chart type
  swanlab/db/utils/chart.py
Labels: bug

#334 Feat/new line chart
  vue/src/charts/package/LineChart.vue
  vue/src/views/charts/ChartsView.vue
  vue/src/views/experiment/pages/chart/ChartPage.vue
Labels: bug, enhancement

#341 record max step and min step
  swanlab/data/run/exp.py
Labels: enhancement

#347 feat/add swanlab.Run
  swanlab/__init__.py
  swanlab/data/__init__.py
Labels: enhancement

#340 Feat/tooltip
  .vscode/extensions.json
  swanlab/data/run/exp.py
  swanlab/server/controller/experiment.py
  vue/src/charts/package/LineChart.vue
  vue/src/i18n/en-US/common.json
  vue/src/i18n/en-US/error.json
  vue/src/i18n/zh-CN/common.json
  vue/src/i18n/zh-CN/error.json
  vue/src/i18n/zh-CN/experiment.json
  vue/src/views/charts/ChartsView.vue
Labels: bug, enhancement

#343 feat/class-video
  swanlab/data/__init__.py
  swanlab/data/modules/__init__.py
  swanlab/data/modules/chart.py
  swanlab/data/modules/video.py
Labels: bug

#351 Update/line chart styles
  vue/src/charts/components/LinChartTooltip.vue
  vue/src/charts/components/SlideBar.vue
  vue/src/charts/package/AudioChart.vue
  vue/src/charts/package/ImageChart.vue
  vue/src/charts/package/LineChart.vue
Labels: bug, UI/UX Enhancement

#354 legend component
  swanlab/server/controller/experiment.py
  vue/src/charts/components/LineChartLegend.vue
  vue/src/charts/package/LineChart.vue
Labels: UI/UX Enhancement

#337 Feature/text chart
  .vscode/launch.json
  swanlab/__init__.py
  swanlab/data/modules/__init__.py
  swanlab/data/modules/text.py
  swanlab/data/utils/file.py
  test/create_experiment.py
  vue/src/charts/components/ChartContainer.vue
  vue/src/charts/components/SlideBar.vue
  vue/src/charts/modules/TextDetail.vue
  vue/src/charts/modules/TextModule.vue
  vue/src/charts/package/TextChart.vue
  vue/src/i18n/en-US/common.json
  vue/src/i18n/zh-CN/common.json
  vue/src/views/experiment/pages/chart/ChartPage.vue
  vue/src/views/experiment/pages/environment/EnvironmentPage.vue
  vue/src/views/experiment/pages/index/components/DataTable.vue
  vue/src/views/experiment/pages/log/LogPage.vue
Labels: enhancement

#362 fix zoom logic
  vue/src/charts/package/ImageChart.vue
Labels: bug

#361 Refactor/log page
  swanlab/server/controller/experiment.py
  vue/src/views/experiment/components/FuncBar.vue
  vue/src/views/experiment/pages/log/LogPage.vue
  vue/src/views/home/components/TableBar.vue
Labels: bug, enhancement

#367 fix: delete charts with experiment destroying
  swanlab/server/controller/experiment.py
Labels: bug

#365 Fixbug/finish time
  swanlab/data/run/exp.py
  swanlab/data/run/main.py
  swanlab/db/db_connect.py
  swanlab/db/migrate/__init__.py
  swanlab/db/migrate/exp_finish_time.py
  swanlab/db/model.py
  swanlab/db/models/experiments.py
  swanlab/log/log.py
  swanlab/server/controller/experiment.py
  test/create_experiment.py
  vue/src/charts/modules/TextDetail.vue
  vue/src/i18n/en-US/common.json
  vue/src/i18n/zh-CN/common.json
  vue/src/layouts/ExperimentLayout.vue
  vue/src/store/modules/experiment.js
  vue/src/store/modules/project.js
  vue/src/utils/time.js
  vue/src/views/experiment/ExperimentView.vue
  vue/src/views/experiment/components/StopButton.vue
Labels: bug, enhancement
