Repository SwanHubX/SwanLab, pull requests merged in 2024-04, with the labels that each got.

#436 feat/fmt code
  swanlab/cli/main.py
  swanlab/data/__init__.py
  swanlab/data/modules/__init__.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
Labels: documentation

#438 Feat/unit test
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  pytest.ini
  test/_server.py
  test/cli_test.py
  test/config/config.json
  test/config/load.yaml
  test/create_experiment.py
  test/start_server.py
  test/unit/pytest_example.py
Labels: documentation

#440 feat/login-test
  .github/workflows/test-pr-to-main.yml
  .gitignore
  pyproject.toml
  requirements-dev.txt
  script/test.py
  swanlab/__init__.py
  swanlab/auth/__init__.py
  swanlab/auth/experiment.py
  swanlab/auth/info.py
  swanlab/auth/login.py
  swanlab/cli/main.py
  swanlab/cli/utils.py
  swanlab/cloud/__init__.py
  swanlab/cloud/_log_collector.py
  swanlab/cloud/_log_sniffer.py
  swanlab/cloud/start_thread.py
  swanlab/cloud/utils.py
  swanlab/data/run/utils.py
  swanlab/data/sdk.py
  swanlab/db/models/experiments.py
  swanlab/db/models/projects.py
  swanlab/env.py
  swanlab/error.py
  swanlab/package.py
  swanlab/server/app.py
  swanlab/server/middleware/common.py
  swanlab/utils/__init__.py
  swanlab/utils/file.py
  swanlab/utils/key.py
  swanlab/utils/token.py
  test/create_experiment.py
  test/unit/auth/pytest_login.py
  test/unit/conftest.py
  test/unit/utils/pytest_key.py
  test/unit/utils/pytest_package.py
  tutils/config.py
Labels: 🐛bug, documentation

#441 Feat/login
  requirements.txt
  swanlab/__init__.py
  swanlab/api/__init__.py
  swanlab/api/auth/__init__.py
  swanlab/api/auth/info.py
  swanlab/api/auth/login.py
  swanlab/cli/main.py
  swanlab/cloud/__init__.py
  swanlab/cloud/_log_collector.py
  swanlab/cloud/_log_sniffer.py
  swanlab/cloud/dog/README.md
  swanlab/cloud/dog/__init__.py
  swanlab/cloud/dog/log_sniffer.py
  swanlab/cloud/start_thread.py
  swanlab/cloud/utils.py
  swanlab/data/__init__.py
  swanlab/data/sdk.py
  swanlab/package.json
  swanlab/package.py
  swanlab/server/middleware/common.py
  swanlab/utils/key.py
  test/unit/auth/pytest_login.py
Labels: enhancement

#444 Feat/watchdog
  swanlab/api/__init__.py
  swanlab/api/auth/login.py
  swanlab/cloud/__init__.py
  swanlab/cloud/_log_collector.py
  swanlab/cloud/dog/log_sniffer.py
  swanlab/cloud/dog/metadata_handle.py
  swanlab/cloud/dog/sniffer_queue.py
  swanlab/cloud/files_types.py
  swanlab/cloud/start_thread.py
  swanlab/cloud/utils.py
  swanlab/data/sdk.py
  swanlab/data/settings.py
  swanlab/error.py
  swanlab/utils/font.py
Labels: enhancement, good attempt

#449 Feat/upload console data
  swanlab/api/__init__.py
  swanlab/api/http.py
  swanlab/api/upload/__init__.py
  swanlab/cloud/_log_collector.py
  swanlab/cloud/files_types.py
  swanlab/cloud/start_thread.py
  swanlab/data/sdk.py
  swanlab/error.py
  swanlab/log/console.py
  swanlab/log/log.py
Labels: enhancement

#450 Upload scalar metrics
  requirements.txt
  swanlab/api/__init__.py
  swanlab/api/auth/__init__.py
  swanlab/api/auth/login.py
  swanlab/api/cos.py
  swanlab/api/http.py
  swanlab/api/info.py
  swanlab/api/upload/__init__.py
  swanlab/cloud/_log_collector.py
  swanlab/data/run/exp.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
  swanlab/data/settings.py
  swanlab/db/models/experiments.py
  swanlab/error.py
  swanlab/utils/font.py
Labels: 🐛bug, enhancement

#451 Feat/house upload
  requirements.txt
  swanlab/api/__init__.py
  swanlab/api/auth/__init__.py
  swanlab/api/auth/login.py
  swanlab/api/cos.py
  swanlab/api/http.py
  swanlab/api/info.py
  swanlab/api/upload/__init__.py
  swanlab/cloud/__init__.py
  swanlab/cloud/_log_collector.py
  swanlab/cloud/dog/log_sniffer.py
  swanlab/cloud/dog/metadata_handle.py
  swanlab/cloud/files_types.py
  swanlab/cloud/start_thread.py
  swanlab/cloud/task_types.py
  swanlab/cloud/utils.py
  swanlab/data/run/exp.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
  swanlab/data/settings.py
  swanlab/db/models/experiments.py
  swanlab/error.py
  swanlab/log/console.py
  swanlab/log/log.py
  swanlab/utils/font.py
Labels: 🐛bug, enhancement

#459 Fix/some bug
  vue/src/charts/modules/AudioModule.vue
  vue/src/charts/package/AudioChart.vue
  vue/src/charts/package/ImageChart.vue
Labels: 🐛 bug

#461 update time.js
  vue/src/utils/time.js
Labels: 🐛 bug

#462 Feat/api
  requirements.txt
  swanlab/api/http.py
  swanlab/cloud/dog/metadata_handle.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
  swanlab/db/models/experiments.py
  swanlab/db/models/namespaces.py
  swanlab/utils/time.py
Labels: 🐛 bug

#464 Feat/org api
  swanlab/api/http.py
  swanlab/data/sdk.py
Labels: 🐛 bug, 📚 documentation, 💪 enhancement

#466 Feat/data down sampling
  swanlab/data/sdk.py
  swanlab/server/controller/experiment.py
  swanlab/server/controller/utils/__init__.py
  swanlab/server/controller/utils/tag.py
  test/unit/conftest.py
  test/unit/server/controller/utils/utils.py
  tutils/config.py
  vue/src/charts/components/LineChartTooltip.vue
  vue/src/charts/package/LineChart.vue
  vue/src/utils/time.js
Labels: 🐛 bug

#467 change entity to workspace
  swanlab/data/sdk.py
Labels: UI/UX Enhancement

#468 Feat/change exp state
  swanlab/api/http.py
  swanlab/api/info.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
Labels: 💪 enhancement

#469 access config api
  swanlab/api/http.py
  swanlab/api/info.py
  swanlab/api/upload/__init__.py
  swanlab/cloud/dog/log_sniffer.py
  swanlab/data/sdk.py
  swanlab/db/models/experiments.py
Labels: 💪 enhancement

#472 add swanlab version
  swanlab/data/system/info.py
Labels: 🐛 bug

#475 add logdir
  swanlab/data/run/main.py
  swanlab/data/settings.py
  swanlab/data/system/info.py
Labels: 🐛 bug, 💪 enhancement

#483 Feat/log add time and epoch
  swanlab/api/upload/__init__.py
  swanlab/data/sdk.py
  swanlab/data/system/bin/apple_gpu_stats
  swanlab/log/console.py
  swanlab/log/log.py
Labels: 💪 enhancement

#487 refactor: swanlog
  swanlab/log/console.py
  vue/src/views/experiment/pages/log/LogPage.vue
Labels: 🐛 bug, 💪 enhancement

#489 fix: upload error
  swanlab/api/http.py
  swanlab/data/sdk.py
Labels: 🐛 bug

#491 refactor/swanlog
  swanlab/api/auth/login.py
  swanlab/cloud/start_thread.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
  swanlab/data/settings.py
  swanlab/log/__init__.py
  swanlab/log/console.py
  swanlab/log/log.py
  swanlab/server/__init__.py
  swanlab/utils/font.py
  test/unit/auth/pytest_login.py
  test/unit/conftest.py
  test/unit/log/pytest_log.py
  tutils/__init__.py
Labels: 🐛 bug, 💪 enhancement

#498 nest_asyncio.apply()
  swanlab/api/__init__.py
  swanlab/data/sdk.py
Labels: 🐛 bug

#499 opt/finish
  requirements.txt
  swanlab/__init__.py
  swanlab/api/__init__.py
  swanlab/api/auth/login.py
  swanlab/api/http.py
  swanlab/data/__init__.py
  swanlab/data/config.py
  swanlab/data/run/__init__.py
  swanlab/data/run/db.py
  swanlab/data/run/exp.py
  swanlab/data/run/main.py
  swanlab/data/run/utils.py
  swanlab/data/sdk.py
  swanlab/data/settings.py
  swanlab/log/log.py
  swanlab/server/controller/experiment.py
  swanlab/server/controller/project.py
  swanlab/utils/__init__.py
  swanlab/utils/file.py
  swanlab/utils/font.py
  test/unit/conftest.py
  test/unit/data/pytest_sdk.py
  test/unit/data/run/pytest_main.py
  test/unit/log/pytest_log.py
  tutils/__init__.py
Labels: 🐛 bug, 💪 enhancement

#508 recreate session
  swanlab/api/http.py
  swanlab/cloud/_log_collector.py
Labels: 🐛 bug

#504 change name when 409
  swanlab/data/run/main.py
  swanlab/data/sdk.py
  swanlab/db/models/experiments.py
  swanlab/db/models/projects.py
  swanlab/log/log.py
  swanlab/utils/font.py
  test/create_experiment.py
Labels: 🐛 bug

#509 Feat/jupyter-notebook-support
  requirements-dev.txt
  swanlab/__init__.py
  swanlab/api/auth/login.py
  swanlab/data/sdk.py
  swanlab/log/console.py
  swanlab/utils/judgment.py
Labels: 💪 enhancement

#511 fix: exp summary table
  vue/src/utils/time.js
  vue/src/views/experiment/pages/index/components/DataTable.vue
Labels: 🐛 bug

#480 Feat/integration-pytorch-lightning
  swanlab/integration/pytorch_lightning.py
Labels: 💪 enhancement

#495 Feat/integration-OpenAI-autolog
  requirements.txt
  swanlab/__init__.py
  swanlab/env.py
  swanlab/integration/huggingface.py
  swanlab/integration/integration_utils/autologging.py
  swanlab/integration/integration_utils/get_modules.py
  swanlab/integration/integration_utils/timer.py
  swanlab/integration/openai/__init__.py
  swanlab/integration/openai/openai.py
  swanlab/integration/openai/resolver.py
Labels: 💪 enhancement

#515 fix event error
  requirements.txt
  swanlab/api/__init__.py
  swanlab/api/auth/login.py
  swanlab/api/http.py
  swanlab/api/info.py
  swanlab/api/upload/__init__.py
  swanlab/cloud/_log_collector.py
  swanlab/cloud/dog/log_sniffer.py
  swanlab/cloud/start_thread.py
  swanlab/cloud/utils.py
  swanlab/data/run/main.py
  swanlab/error.py
  swanlab/package.json
  swanlab/utils/font.py
  test/unit/auth/pytest_login.py
Labels: 🐛 bug

#484 Feat/integration-huggingface-transformers
  swanlab/data/__init__.py
  swanlab/integration/huggingface.py
Labels: 💪 enhancement

#516 error tip when proj error
  swanlab/data/sdk.py
  swanlab/db/models/projects.py
  swanlab/log/__init__.py
  swanlab/utils/__init__.py
  swanlab/utils/file.py
  test/unit/utils/pytest_file.py
Labels: 🐛 bug

#517 Feat/integration-mmengine-support
  swanlab/integration/mmengine.py
Labels: 💪 enhancement

#520 Feat/integration zhipu ai
  swanlab/integration/integration_utils/autologging.py
  swanlab/integration/zhipuai/__init__.py
  swanlab/integration/zhipuai/resolver.py
  swanlab/integration/zhipuai/zhipuai.py
Labels: 💪 enhancement, 🌍 prepare for the future
