Repository SwanHubX/SwanLab, pull requests merged in 2024-01, with the labels that each got.

#129 Refactor/env
  .vscode/settings.json
  swanlab/__init__.py
  swanlab/data/__init__.py
  swanlab/data/modules/__init__.py
  swanlab/data/modules/base.py
  swanlab/data/modules/chart.py
  swanlab/data/run/__init__.py
  swanlab/data/run/exp.py
  swanlab/data/run/main.py
  swanlab/data/run/utils.py
  swanlab/data/sdk.py
  swanlab/data/settings.py
  swanlab/data/system.py
  swanlab/database/__init__.py
  swanlab/database/chart.py
  swanlab/database/experiment.py
  swanlab/database/main.py
  swanlab/database/modules/__init__.py
  swanlab/database/project.py
  swanlab/database/table.py
  swanlab/database/utils.py
  swanlab/env.py
  swanlab/log/__init__.py
  swanlab/log/log.py
  swanlab/server/__init__.py
  swanlab/server/api/experiment.py
  swanlab/server/api/project.py
  swanlab/server/module/models/project.py
  swanlab/server/router.py
  swanlab/server/settings.py
  swanlab/server/web.py
  swanlab/utils/file.py
  test/create_experiment.py
  test/start_server.py
  test/test_logging/app.py
  test/test_wandb.py
Labels: bug, enhancement

#130 Fixbug/duplicate name
  swanlab/server/api/experiment.py
  swanlab/server/api/project.py
Labels: bug

#132 fix #100
  swanlab/cli/main.py
  swanlab/cli/utils.py
Labels: bug

#134 Feature/message
  vue/src/App.vue
  vue/src/assets/iconfont.js
  vue/src/components/HomeSiderBar.vue
  vue/src/components/config-editor/ConfigEditor.vue
  vue/src/components/config-editor/EditorWrap.vue
  vue/src/components/message/SLMessage.vue
  vue/src/components/message/SLMessages.vue
  vue/src/components/message/index.js
  vue/src/components/table/SLTable.vue
  vue/src/i18n/en-US/common.json
  vue/src/utils/browser.js
  vue/src/views/experiment/pages/index/components/ExperimentHeader.vue
Labels: enhancement

#135 add confirm
  tailwind.config.js
  vue/src/App.vue
  vue/src/components/HomeSiderBar.vue
  vue/src/components/SLButton.vue
  vue/src/components/SLHelp.vue
  vue/src/components/SLStatusLabel.vue
  vue/src/components/SLTable.vue
  vue/src/components/comfirm/SLComfirm.vue
  vue/src/components/comfirm/index.js
  vue/src/components/config-editor/ConfigEditor.vue
  vue/src/components/config-editor/EditorWrap.vue
  vue/src/components/table/SLTable.vue
  vue/src/components/table/TableCell.vue
  vue/src/layouts/ExperimentLayout.vue
  vue/src/layouts/MainLayout.vue
  vue/src/theme/color.min.css
  vue/src/theme/color.scss
  vue/src/views/error/pages/404.vue
  vue/src/views/experiment/components/TabsHeader.vue
  vue/src/views/experiment/pages/chart/components/ChartsContainer.vue
  vue/src/views/experiment/pages/chart/components/PannelButton.vue
  vue/src/views/experiment/pages/log/LogPage.vue
  vue/src/views/home/HomeView.vue
Labels: enhancement

#138 default project name
  swanlab/data/run/main.py
  swanlab/data/settings.py
Labels: enhancement

#149 fix: 404 to homepage
  vue/src/router/index.js
  vue/src/store/modules/project.js
  vue/src/views/error/pages/404.vue
  vue/src/views/error/pages/NotFound.vue
  vue/src/views/home/HomeView.vue
Labels: bug, UI/UX Enhancement

#144 feature: message style
  vue/src/components/message/SLMessage.vue
  vue/src/components/message/index.js
Labels: UI/UX Enhancement

#154 message above all
  tailwind.config.js
  vue/src/App.vue
  vue/src/components/message/SLMessages.vue
Labels: bug

#151 when log_level is None
  swanlab/data/run/main.py
Labels: bug

#152 fix number formatter
  swanlab/server/api/experiment.py
  swanlab/server/api/project.py
  vue/src/views/experiment/pages/chart/components/package/LineChart.vue
  vue/src/views/experiment/pages/index/components/ExperimentConfig.vue
Labels: bug

#156 Fixbug/table style
  vue/src/components/SLTable.vue
  vue/src/components/table/SLTable.vue
  vue/src/components/table/TableCell.vue
  vue/src/components/table/index.ts
  vue/src/views/experiment/pages/index/components/ExperimentConfig.vue
  vue/src/views/home/HomeView.vue
  vue/src/views/home/components/ExperimentName.vue
Labels: bug, enhancement, UI/UX Enhancement

#157 set -1 when crashed
  swanlab/data/run/main.py
Labels: bug

#158 Feat name limit
  pyproject.toml
  swanlab/data/run/main.py
  swanlab/data/run/utils.py
  swanlab/server/api/experiment.py
  swanlab/server/api/project.py
  swanlab/utils/file.py
  test/create_experiment.py
  vue/src/components/config-editor/EditorWrap.vue
  vue/src/i18n/en-US/common.json
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/zh-CN/experiment.json
  vue/src/views/experiment/pages/index/components/ExperimentHeader.vue
  vue/src/views/experiment/pages/index/components/StopButton.vue
Labels: enhancement

#162 UI/styles
  swanlab/data/system.py
  test/test_system.py
  vue/src/components/SLButton.vue
  vue/src/components/SLDelete.vue
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/zh-CN/experiment.json
  vue/src/views/experiment/pages/index/components/StopButton.vue
Labels: UI/UX Enhancement

#160 v0.1.3
  swanlab/package.json
Labels: enhancement

#173 Feature/log operation
  vue/src/components/SLOperation.vue
  vue/src/components/SLSearch.vue
  vue/src/views/experiment/pages/log/LogPage.vue
Labels: enhancement, UI/UX Enhancement

#169 get memory size
  swanlab/data/system.py
Labels: enhancement

#171 test: add config and example with vitest and pytest
  .prettierignore
  .vscode/extensions.json
  jsconfig.json
  package.json
  test/unit/utils/test_package.py
  vitest.config.ts
  vue/src/theme/color.min.css
  vue/test/unit/utils/common.test.js
Labels: enhancement

#175 fix readme format
  README.md
  README_zh-hans.md
Labels: bug

#181 Refactor/layout
  jsconfig.json
  swanlab/data/system.py
  vue/src/App.vue
  vue/src/assets/iconfont.js
  vue/src/components/SLButton.vue
  vue/src/components/SLSearch.vue
  vue/src/components/comfirm/index.js
  vue/src/components/config-editor/ConfigEditor.vue
  vue/src/components/config-editor/DeleteButton.vue
  vue/src/components/config-editor/EditorWrap.vue
  vue/src/components/config-editor/README
  vue/src/i18n/en-US/common.json
  vue/src/i18n/en-US/error.json
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/zh-CN/common.json
  vue/src/i18n/zh-CN/experiment.json
  vue/src/layouts/ExperimentLayout.vue
  vue/src/layouts/HomeLayout.vue
  vue/src/layouts/MainLayout.vue
  vue/src/layouts/main/MainLayout.vue
  vue/src/layouts/main/components/HeaderBar.vue
  vue/src/layouts/main/components/SideBar.vue
  vue/src/main.js
  vue/src/router/index.js
  vue/src/store/modules/experiment.js
  vue/src/style.scss
  vue/src/theme/color.min.css
  vue/src/views/error/ErrorView.vue
  vue/src/views/error/pages/InitError.vue
  vue/src/views/experiment/ExperimentView.vue
  vue/src/views/experiment/components/ExtendBlock.vue
  vue/src/views/experiment/components/FuncBar.vue
  vue/src/views/experiment/components/TabsHeader.vue
  vue/src/views/experiment/pages/chart/ChartPage.vue
  vue/src/views/experiment/pages/chart/components/ChartsContainer.vue
  vue/src/views/experiment/pages/environment/EnvironmentPage.vue
  vue/src/views/experiment/pages/environment/components/EnvItem.vue
  vue/src/views/experiment/pages/environment/components/EnvItems.vue
  vue/src/views/experiment/pages/environment/components/SiderNav.vue
  vue/src/views/experiment/pages/environment/pages/EnvDependencies.vue
  vue/src/views/experiment/pages/environment/pages/EnvIndex.vue
  vue/src/views/experiment/pages/index/components/ExperimentHeader.vue
  vue/src/views/experiment/pages/log/LogPage.vue
  vue/src/views/home/HomeView.vue
Labels: enhancement, good attempt

#176 delete useless code
  test/test_bug.py
  test/test_catch_error.py
  test/test_consoler.py
  test/test_database_create.py
  test/test_flock.py
  test/test_get_console.py
  test/test_logging/__init__.py
  test/test_logging/app.py
  test/test_logging/test1.py
  test/test_logging/test2.py
  test/test_system.py
  test/test_wandb.py
Labels: bug

#183 Feature/func bar
  swanlab/server/api/experiment.py
  vue/src/assets/iconfont.js
  vue/src/components/SLButton.vue
  vue/src/components/SLCopy.vue
  vue/src/components/SLSearch.vue
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/zh-CN/experiment.json
  vue/src/utils/browser.js
  vue/src/views/experiment/components/FuncBar.vue
  vue/src/views/experiment/pages/environment/pages/EnvDependencies.vue
  vue/src/views/experiment/pages/index/components/ExperimentConfig.vue
  vue/src/views/experiment/pages/log/LogPage.vue
Labels: enhancement

#182 fix header layout
  vue/src/layouts/main/components/HeaderBar.vue
Labels: bug, UI/UX Enhancement

#184 bugfix: requirements '@file' problem
  swanlab/data/system.py
Labels: bug

#187 Feature/files
  swanlab/data/run/main.py
  swanlab/data/settings.py
  swanlab/data/system.py
  swanlab/server/api/experiment.py
  swanlab/server/settings.py
  vue/src/components/SLLoading.vue
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/zh-CN/experiment.json
  vue/src/router/index.js
  vue/src/views/experiment/pages/environment/components/SiderNav.vue
  vue/src/views/experiment/pages/environment/pages/EnvRequirements.vue
Labels: enhancement

#188 change error code
  swanlab/server/api/experiment.py
  swanlab/server/api/project.py
  swanlab/server/module/resp.py
Labels: invalid

#191 Fixbug/log params
  swanlab/data/system.py
  swanlab/log/log.py
Labels: enhancement

#186 Feat/env params
  .gitignore
  swanlab/cli/main.py
  swanlab/cli/utils.py
  swanlab/data/run/__init__.py
  swanlab/data/sdk.py
  swanlab/data/settings.py
  swanlab/data/utils/file.py
  swanlab/env.py
  swanlab/log/__init__.py
  swanlab/log/log.py
  swanlab/server/__init__.py
  swanlab/server/api/project.py
  swanlab/utils/file.py
  test/create_experiment.py
  vue/src/layouts/HomeLayout.vue
  vue/src/views/experiment/pages/environment/components/EnvItems.vue
Labels: enhancement, good attempt

#192 fix: params
  swanlab/log/log.py
Labels: bug

#180 Feat/Increase support for the calling method of 'run.config.lr'.
  swanlab/data/run/main.py
  test/create_experiment.py
Labels: enhancement

#196 Feature/format num
  .husky/pre-push
  package.json
  swanlab/data/run/exp.py
  swanlab/server/api/experiment.py
  swanlab/server/api/project.py
  test/create_experiment.py
  vue/src/App.vue
  vue/src/utils/common.js
  vue/src/views/experiment/pages/chart/ChartPage.vue
  vue/src/views/experiment/pages/chart/components/package/LineChart.vue
  vue/src/views/experiment/pages/chart/components/package/README.md
  vue/src/views/experiment/pages/index/components/ExperimentConfig.vue
  vue/src/views/home/HomeView.vue
  vue/test/unit/utils/common.test.js
Labels: enhancement

#198 feat/v0.1.4
  swanlab/data/run/main.py
  swanlab/package.json
  swanlab/server/api/experiment.py
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/zh-CN/experiment.json
  vue/src/store/modules/experiment.js
  vue/src/store/modules/project.js
  vue/src/views/experiment/ExperimentView.vue
  vue/src/views/experiment/components/FuncBar.vue
  vue/src/views/experiment/pages/environment/pages/EnvRequirements.vue
  vue/src/views/experiment/pages/index/components/StopButton.vue
  vue/src/views/experiment/pages/log/LogPage.vue
Labels: bug, documentation, enhancement

#200 feat: automatic release
  .github/workflows/publish-to-pypi.yml
Labels: documentation, enhancement

#216 Feat/UI enhancement
  vue/src/assets/iconfont.js
  vue/src/components/SLCheck.vue
  vue/src/components/SLStatusLabel.vue
  vue/src/components/table/SLTable.vue
  vue/src/i18n/en-US/common.json
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/en-US/home.json
  vue/src/i18n/zh-CN/common.json
  vue/src/i18n/zh-CN/experiment.json
  vue/src/layouts/ExperimentLayout.vue
  vue/src/layouts/HomeLayout.vue
  vue/src/layouts/main/MainLayout.vue
  vue/src/layouts/main/components/HeaderBar.vue
  vue/src/layouts/main/components/SideBar.vue
  vue/src/views/experiment/ExperimentView.vue
  vue/src/views/experiment/components/StopButton.vue
  vue/src/views/experiment/pages/environment/pages/EnvIndex.vue
  vue/src/views/experiment/pages/index/components/ExperimentConfig.vue
  vue/src/views/experiment/pages/index/components/ExperimentHeader.vue
  vue/src/views/home/HomeView.vue
  vue/src/views/home/components/TableBar.vue
Labels: bug, UI/UX Enhancement

#222 Fixbug/UI
  vue/src/assets/iconfont.js
  vue/src/layouts/ExperimentLayout.vue
Labels: bug

#218 Annotation swanlog.warning
  swanlab/data/system.py
Labels: bug

#215 Allow space
  swanlab/data/run/exp.py
  swanlab/data/run/utils.py
  swanlab/utils/file.py
Labels: bug

#232 Feat/yaxis line
  test/create_experiment.py
  vue/src/views/experiment/pages/chart/components/package/LineChart.vue
Labels: UI/UX Enhancement

#231 Feature/table bar
  vue/src/components/SLButton.vue
  vue/src/components/SLCheck.vue
  vue/src/components/SLSearch.vue
  vue/src/i18n/en-US/home.json
  vue/src/layouts/ExperimentLayout.vue
  vue/src/layouts/HomeLayout.vue
  vue/src/utils/time.js
  vue/src/views/home/HomeView.vue
  vue/src/views/home/components/TableBar.vue
Labels: enhancement

#238 feat: add json_serializable and optimize __check_cofig function
  swanlab/data/run/main.py
  swanlab/data/run/utils.py
Labels: bug

#244 bugfix: config
  swanlab/data/run/main.py
Labels: bug

#236 Refactor/use orm
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  requirements.txt
  swanlab/cli/main.py
  swanlab/data/run/__init__.py
  swanlab/data/run/db.py
  swanlab/data/run/exp.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
  swanlab/data/settings.py
  swanlab/db/__init__.py
  swanlab/db/docs/Errors.md
  swanlab/db/docs/README.md
  swanlab/db/error.py
  swanlab/db/model.py
  swanlab/db/models/__init__.py
  swanlab/db/models/charts.py
  swanlab/db/models/displays.py
  swanlab/db/models/experiments.py
  swanlab/db/models/namespaces.py
  swanlab/db/models/projects.py
  swanlab/db/models/sources.py
  swanlab/db/models/tags.py
  swanlab/env.py
  swanlab/server/__init__.py
  swanlab/server/api/project.py
  swanlab/server/app.py
  swanlab/server/controller/experiment.py
  swanlab/server/controller/project.py
  swanlab/server/middleware/common.py
  swanlab/server/module/__init__.py
  swanlab/server/module/models/project.py
  swanlab/server/router/experiment.py
  swanlab/server/router/project.py
  swanlab/server/settings.py
  test/_server.py
  test/create_experiment.py
  test/db/__init__.py
  test/db/test_chart.py
  test/db/test_display.py
  test/db/test_experiment.py
  test/db/test_namespace.py
  test/db/test_project.py
  test/db/test_tag.py
  test/start_server.py
  vue/src/layouts/ExperimentLayout.vue
  vue/src/layouts/HomeLayout.vue
  vue/src/layouts/main/components/SideBar.vue
  vue/src/store/modules/experiment.js
  vue/src/store/modules/project.js
  vue/src/views/experiment/ExperimentView.vue
  vue/src/views/experiment/components/StopButton.vue
  vue/src/views/experiment/pages/chart/ChartPage.vue
  vue/src/views/experiment/pages/chart/components/ChartContainer.vue
  vue/src/views/experiment/pages/chart/components/package/LineChart.vue
  vue/src/views/experiment/pages/index/components/ExperimentConfig.vue
  vue/src/views/home/HomeView.vue
Labels: enhancement

#250 feat: hover copy
  swanlab/server/controller/project.py
  swanlab/server/router/project.py
  vue/src/components/SLCopy.vue
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/en-US/home.json
  vue/src/i18n/zh-CN/experiment.json
  vue/src/i18n/zh-CN/home.json
  vue/src/store/modules/project.js
  vue/src/views/experiment/pages/environment/components/EnvItem.vue
  vue/src/views/experiment/pages/environment/components/EnvItems.vue
  vue/src/views/experiment/pages/environment/pages/EnvIndex.vue
  vue/src/views/home/HomeView.vue
Labels: enhancement

#248 Feat/swanlab.config
  swanlab/__init__.py
  swanlab/data/__init__.py
  swanlab/data/run/__init__.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
  swanlab/data/settings.py
Labels: enhancement

#251 Feat/readme v0.1.5
  README.md
  README_zh-hans.md
Labels: bug

#253 feat/v0.1.5
  README.md
  README_zh-hans.md
  swanlab/cli/main.py
  swanlab/cli/utils.py
  swanlab/data/run/exp.py
  swanlab/data/sdk.py
  swanlab/package.json
  swanlab/server/controller/project.py
  swanlab/utils/__init__.py
  swanlab/utils/package.py
  test/create_experiment.py
  vue/src/components/SLCheck.vue
  vue/src/components/SLSearch.vue
  vue/src/components/message/SLMessage.vue
  vue/src/components/table/SLTable.vue
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/zh-CN/experiment.json
  vue/src/views/experiment/pages/chart/ChartPage.vue
  vue/src/views/experiment/pages/chart/components/EmptyExperiment.vue
  vue/src/views/experiment/pages/chart/components/package/LineChart.vue
  vue/src/views/experiment/pages/environment/components/EnvItem.vue
  vue/src/views/experiment/pages/environment/pages/EnvIndex.vue
  vue/src/views/experiment/pages/index/components/ExperimentConfig.vue
  vue/src/views/home/components/TableBar.vue
Labels: bug, enhancement

#258 fix: copy
  vue/src/views/experiment/pages/environment/components/EnvItem.vue
Labels: bug

#272 fix color
  tailwind.config.js
  vue/src/layouts/main/components/HeaderBar.vue
  vue/src/layouts/main/components/HeaderIcon.vue
  vue/src/theme/color.scss
Labels: bug, UI/UX Enhancement

#273 Fixbug/invalid tag
  swanlab/data/run/exp.py
  swanlab/data/run/main.py
  swanlab/server/api/experiment.py
  swanlab/server/api/project.py
  swanlab/server/controller/experiment.py
  swanlab/server/controller/project.py
  test/create_experiment.py
  vue/src/components/SLSearch.vue
  vue/src/components/table/index.ts
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/zh-CN/experiment.json
  vue/src/views/experiment/pages/chart/components/package/LineChart.vue
  vue/src/views/experiment/pages/index/IndexPage.vue
  vue/src/views/experiment/pages/index/components/DataTable.vue
  vue/src/views/experiment/pages/index/components/ExperimentConfig.vue
  vue/src/views/experiment/pages/index/components/TableLine.vue
  vue/src/views/home/HomeView.vue
  vue/src/views/home/components/ExprTable.vue
Labels: bug

#275 fix: overflow
  vue/src/views/home/components/ExprTable.vue
Labels: bug

#278 Feat/update font family
  vue/src/assets/font/SourceSansPro-Regular.ttf
  vue/src/layouts/ExperimentLayout.vue
  vue/src/layouts/HomeLayout.vue
  vue/src/layouts/main/components/SideBar.vue
  vue/src/style.scss
  vue/src/views/experiment/pages/environment/components/SiderNav.vue
Labels: UI/UX Enhancement

#277 Feature/custom log
  swanlab/data/run/exp.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
  swanlab/log/__init__.py
  swanlab/log/log.py
  test/create_experiment.py
Labels: bug

#271 Feature/experiment table
  swanlab/cli/main.py
  swanlab/package.json
  swanlab/utils/package.py
  tailwind.config.js
  vue/src/assets/font/SourceSansPro-Regular.ttf
  vue/src/components/SLSearch.vue
  vue/src/layouts/ExperimentLayout.vue
  vue/src/layouts/HomeLayout.vue
  vue/src/layouts/main/components/SideBar.vue
  vue/src/style.scss
  vue/src/theme/color.scss
  vue/src/views/experiment/pages/environment/components/SiderNav.vue
  vue/src/views/experiment/pages/index/components/DataTable.vue
  vue/src/views/experiment/pages/index/components/ExperimentConfig.vue
  vue/src/views/experiment/pages/index/components/ExperimentHeader.vue
  vue/src/views/experiment/pages/index/components/TableLine.vue
Labels: bug, enhancement

#282 Bugfix/v0.1.6
  swanlab/data/run/main.py
  swanlab/db/model.py
  swanlab/server/controller/experiment.py
  swanlab/server/controller/project.py
  test/create_experiment.py
  vue/src/views/experiment/pages/index/components/ExperimentConfig.vue
Labels: bug

#284 Feat/system hardware
  swanlab/data/system.py
  vue/src/i18n/en-US/experiment.json
  vue/src/i18n/zh-CN/experiment.json
  vue/src/layouts/ExperimentLayout.vue
  vue/src/router/index.js
  vue/src/views/experiment/components/FuncBar.vue
  vue/src/views/experiment/pages/environment/EnvironmentPage.vue
  vue/src/views/experiment/pages/environment/components/EnvGPUItem.vue
  vue/src/views/experiment/pages/environment/components/EnvItem.vue
  vue/src/views/experiment/pages/environment/components/SiderNav.vue
  vue/src/views/experiment/pages/environment/pages/EnvHardware.vue
  vue/src/views/experiment/pages/environment/pages/EnvIndex.vue
  vue/src/views/experiment/pages/environment/pages/EnvRequirements.vue
Labels: UI/UX Enhancement

#287 Feature/color
  swanlab/data/system.py
  tailwind.config.js
  vue/src/theme/color.scss
  vue/src/views/experiment/components/FuncBar.vue
  vue/src/views/experiment/pages/chart/ChartPage.vue
  vue/src/views/experiment/pages/chart/components/ChartContainer.vue
  vue/src/views/experiment/pages/environment/EnvironmentPage.vue
  vue/src/views/experiment/pages/environment/components/EnvGPUItem.vue
  vue/src/views/experiment/pages/environment/components/SiderNav.vue
  vue/src/views/experiment/pages/environment/pages/EnvHardware.vue
  vue/src/views/experiment/pages/environment/pages/EnvIndex.vue
  vue/src/views/experiment/pages/environment/pages/EnvRequirements.vue
Labels: UI/UX Enhancement

#286 Feat/project nav
  .vscode/settings.json
  package.json
  swanlab/data/system.py
  tailwind.config.js
  vite.config.js
  vue/src/assets/iconfont.js
  vue/src/components/SLSearch.vue
  vue/src/i18n/en-US/common.json
  vue/src/i18n/en-US/error.json
  vue/src/i18n/zh-CN/common.json
  vue/src/i18n/zh-CN/error.json
  vue/src/layouts/ExperimentLayout.vue
  vue/src/layouts/main/MainLayout.vue
  vue/src/layouts/main/components/HeaderBar.vue
  vue/src/layouts/main/components/SideBar.vue
  vue/src/mock/index.js
  vue/src/mock/modules/experiment.js
  vue/src/mock/modules/project.js
  vue/src/router/index.js
  vue/src/store/modules/project.js
  vue/src/theme/color.scss
  vue/src/views/charts/ChartsView.vue
  vue/src/views/experiment/components/FuncBar.vue
  vue/src/views/experiment/pages/chart/ChartPage.vue
  vue/src/views/experiment/pages/chart/components/ChartContainer.vue
  vue/src/views/experiment/pages/chart/components/ChartsContainer.vue
  vue/src/views/experiment/pages/environment/EnvironmentPage.vue
  vue/src/views/experiment/pages/environment/components/EnvGPUItem.vue
  vue/src/views/experiment/pages/environment/components/SiderNav.vue
  vue/src/views/experiment/pages/environment/pages/EnvHardware.vue
  vue/src/views/experiment/pages/environment/pages/EnvIndex.vue
  vue/src/views/experiment/pages/environment/pages/EnvRequirements.vue
  vue/src/views/home/HomeView.vue
Labels: UI/UX Enhancement

#288 bug fix: delete experiment
  swanlab/db/models/experiments.py
Labels: bug

#290 Feat/line chart
  .vscode/swanlab.code-snippets
  swanlab/db/models/experiments.py
  swanlab/server/controller/experiment.py
  swanlab/server/controller/project.py
  swanlab/utils/__init__.py
  swanlab/utils/font.py
  test/create_experiment.py
  vue/src/charts/ChartsContainer.vue
  vue/src/charts/README.md
  vue/src/charts/components/ChartContainer.vue
  vue/src/charts/components/PannelButton.vue
  vue/src/charts/package/LineChart.vue
  vue/src/charts/package/UnknownChart.vue
  vue/src/charts/package/utils.js
  vue/src/components/config-editor/EditorWrap.vue
  vue/src/layouts/ExperimentLayout.vue
  vue/src/store/index.js
  vue/src/store/modules/experiment.js
  vue/src/store/modules/project.js
  vue/src/views/experiment/ExperimentView.vue
  vue/src/views/experiment/components/StopButton.vue
  vue/src/views/experiment/pages/chart/ChartPage.vue
  vue/src/views/experiment/pages/chart/components/ChartsContainer.vue
  vue/src/views/experiment/pages/chart/components/package/README.md
  vue/src/views/experiment/pages/environment/components/EnvGPUItem.vue
  vue/src/views/experiment/pages/environment/pages/EnvHardware.vue
  vue/src/views/experiment/pages/environment/pages/EnvIndex.vue
  vue/src/views/experiment/pages/environment/pages/EnvRequirements.vue
  vue/src/views/experiment/pages/index/components/ExperimentConfig.vue
  vue/src/views/experiment/pages/index/components/ExperimentHeader.vue
  vue/src/views/experiment/pages/log/LogPage.vue
Labels: bug, documentation, enhancement

#279 Feat/audio chart
  swanlab/data/modules/audio.py
  swanlab/data/modules/chart.py
  swanlab/data/modules/image.py
Labels: enhancement
