Repository SwanHubX/SwanLab, pull requests merged in 2024-05, with the labels that each got.

#526 bugfix: omegaconf
  swanlab/data/sdk.py
Labels: 🐛 bug

#531 refactor callbacks
  swanlab/data/callback_cloud.py
  swanlab/data/callback_local.py
  swanlab/data/modules/_utils.py
  swanlab/data/modules/audio.py
  swanlab/data/modules/image.py
  swanlab/data/modules/object_3d.py
  swanlab/data/modules/video.py
  swanlab/data/run/__init__.py
  swanlab/data/run/callback.py
  swanlab/data/run/exp.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
  swanlab/data/utils/file.py
  swanlab/data/utils/model.py
  test/create_experiment.py
  tutils/__init__.py
Labels: 🐛 bug, 💪 enhancement

#532 change api host
  swanlab/package.json
Labels: 💪 enhancement

#542 Feat/better value error
  swanlab/data/run/exp.py
Labels: 💪 enhancement

#544 feat: export line chart as png
  .vscode/launch.json
  package.json
  test/start_server.py
  vue/src/charts/components/ChartContainer.vue
  vue/src/charts/components/ExportImage.vue
  vue/src/charts/components/InputSlideBar.vue
  vue/src/charts/components/LineChartLegend.vue
  vue/src/charts/components/PanelButton.vue
  vue/src/charts/package/LineChart.vue
  vue/src/components/confirm/SLConfirm.vue
  vue/src/docs/chart.js
  vue/src/i18n/en-US/chart.json5
  vue/src/i18n/zh-CN/chart.json5
  vue/src/style.scss
  vue/src/utils/chart.js
  vue/src/utils/common.js
  vue/src/views/experiment/components/StopButton.vue
Labels: 💪 enhancement

#549 fix api error
  swanlab/api/upload/__init__.py
  swanlab/api/upload/model.py
  swanlab/cloud/_log_collector.py
  test/create_error_chart.py
Labels: 🐛 bug

#552 update linechart style
  vue/src/charts/components/ExportImage.vue
  vue/src/charts/package/LineChart.vue
Labels: 🐛 bug

#556 Feat/Integration-fastai
  swanlab/integration/fastai.py
Labels: 💪 enhancement

#560 Feat/Integration-Ultralytics
  swanlab/integration/ultralytics.py
Labels: 💪 enhancement

#562 feat: disabled api for SLCkeck.vue
  vue/src/components/SLCheck.vue
Labels: 💪 enhancement

#568 Revert "fix: Image-matplotlib"
  swanlab/data/run/exp.py
Labels: 🐛 bug

#543 add operator
  swanlab/api/http.py
  swanlab/api/info.py
  swanlab/data/callback_cloud.py
  swanlab/data/callback_local.py
  swanlab/data/config.py
  swanlab/data/modules/audio.py
  swanlab/data/modules/image.py
  swanlab/data/modules/object_3d.py
  swanlab/data/modules/text.py
  swanlab/data/modules/video.py
  swanlab/data/run/callback.py
  swanlab/data/run/exp.py
  swanlab/data/run/main.py
  swanlab/data/run/operator.py
  swanlab/data/sdk.py
  swanlab/data/settings.py
  swanlab/db/__init__.py
  swanlab/db/callback.py
  swanlab/db/models/experiments.py
  swanlab/env.py
  swanlab/log/log.py
  swanlab/package.py
  test/create_experiment.py
  test/unit/data/pytest_sdk.py
  test/unit/data/run/pytest_main.py
  test/unit/pytest_env.py
Labels: 📚 documentation, 💪 enhancement

#566 Integration-test-script
  .gitignore
  test/integration/.gitignore
  test/integration/README.md
  test/integration/fastai/fastai_train.py
  test/integration/fastai/requirements.txt
  test/integration/huggingface/requirements.txt
  test/integration/huggingface/transformers_bert_train.py
  test/integration/lightning/lightning_base.py
  test/integration/lightning/lightning_train.py
  test/integration/lightning/requirements.txt
  test/integration/sb3/requirements.txt
  test/integration/sb3/sb3_PPO.py
  test/integration/ultralytics/requirements.txt
  test/integration/ultralytics/ultralytics_classifer.py
  test/integration/ultralytics/ultralytics_detection.py
  test/integration/ultralytics/ultralytics_pose.py
  test/integration/ultralytics/ultralytics_segmentation.py
Labels: 📚 documentation, good attempt

#571 v0.3.4
  swanlab/package.json
Labels: 💪 enhancement

#573 install console
  swanlab/data/callback_cloud.py
  swanlab/package.json
Labels: 🐛 bug

#578 update env test
  swanlab/api/auth/login.py
  swanlab/data/callback_cloud.py
  swanlab/env.py
  swanlab/package.py
  test/unit/auth/pytest_login.py
  test/unit/conftest.py
  test/unit/data/pytest_sdk.py
  test/unit/pytest_env.py
  tutils/__init__.py
  tutils/config.py
  tutils/utils.py
Labels: 🐛 bug

#583 Feat/ultralytics-integration-ddp
  swanlab/integration/ultralytics.py
Labels: 🐛 bug

#598 fix cos
  swanlab/api/cos.py
  swanlab/api/http.py
  swanlab/package.json
  test/unit/api/auth/pytest_login.py
  test/unit/api/pytest_http.py
  test/unit/pytest_package.py
  test/unit/utils/pytest_package.py
Labels: 🐛 bug
