Repository SwanHubX/SwanLab, pull requests merged in 2024-03, with the labels that each got.

#372 fix: undefined table value
  vue/src/views/home/HomeView.vue
Labels: bug

#383 Fixbug/show patch
  .vscode/extensions.json
  vue/src/charts/components/ChartContainer.vue
  vue/src/layouts/main/components/SideBar.vue
  vue/src/utils/common.js
Labels: bug

#389 Feature/keyboard
  .vscode/settings.json
  swanlab/server/controller/experiment.py
  test/create_experiment.py
  vue/src/charts/components/SlideBar.vue
  vue/src/charts/modules/TextDetail.vue
  vue/src/charts/modules/TextModule.vue
  vue/src/charts/package/AudioChart.vue
  vue/src/charts/package/ImageChart.vue
  vue/src/charts/package/LineChart.vue
  vue/src/charts/package/TextChart.vue
  vue/src/components/SLModal.vue
Labels: bug, enhancement

#392 Feat/line chart smooth
  .eslintrc-auto-import.json
  .eslintrc.cjs
  jsconfig.json
  vite.config.js
  vue/src/assets/iconfont.js
  vue/src/charts/ChartsDashboard.vue
  vue/src/charts/components/ChartContainer.vue
  vue/src/charts/components/ChartsContainer.vue
  vue/src/charts/components/LinChartTooltip.vue
  vue/src/charts/components/SlideBar.vue
  vue/src/charts/components/SmoothButton.vue
  vue/src/charts/package/LineChart.vue
  vue/src/charts/package/smooth.js
  vue/src/charts/package/utils.js
  vue/src/components/SLSlideBar.vue
  vue/src/components/menu/SLMenu.vue
  vue/src/components/menu/SLMenuItem.vue
  vue/src/components/menu/SLMenuItems.vue
  vue/src/i18n/en-US/common.json
  vue/src/i18n/zh-CN/common.json
  vue/src/layouts/ExperimentLayout.vue
  vue/src/layouts/HomeLayout.vue
  vue/src/layouts/main/MainLayout.vue
  vue/src/layouts/main/components/SideBar.vue
  vue/src/style.scss
  vue/src/views/charts/ChartsView.vue
  vue/src/views/charts/components/ChartsPage.vue
  vue/src/views/experiment/pages/chart/ChartPage.vue
Labels: enhancement

#390 Feat/group folding
  swanlab/db/db_connect.py
  swanlab/db/migrate/__init__.py
  swanlab/db/migrate/namespace_opened.py
  swanlab/db/models/namespaces.py
  swanlab/server/app.py
  swanlab/server/controller/namespace.py
  swanlab/server/router/namespace.py
  vue/src/charts/ChartsDashboard.vue
  vue/src/charts/components/ChartsContainer.vue
  vue/src/views/charts/ChartsView.vue
  vue/src/views/charts/components/ChartsPage.vue
Labels: bug

#397 Feat/pin hidden
  swanlab/db/db_connect.py
  swanlab/db/migrate/__init__.py
  swanlab/db/migrate/chart.py
  swanlab/db/migrate/experiment.py
  swanlab/db/migrate/namespace.py
  swanlab/db/migrate/project.py
  swanlab/db/migrate/tag.py
  swanlab/db/models/charts.py
  swanlab/db/models/experiments.py
  swanlab/db/models/namespaces.py
  swanlab/db/models/projects.py
  swanlab/server/app.py
  swanlab/server/controller/chart.py
  swanlab/server/controller/db.py
  swanlab/server/controller/experiment.py
  swanlab/server/controller/namespace.py
  swanlab/server/controller/project.py
  swanlab/server/controller/utils/__init__.py
  swanlab/server/controller/utils/charts.py
  swanlab/server/middleware/common.py
  swanlab/server/module/__init__.py
  swanlab/server/module/models/experiment.py
  swanlab/server/module/models/project.py
  swanlab/server/module/models/tag.py
  swanlab/server/router/chart.py
  swanlab/server/router/namespace.py
  test/db/test_pinned.py
  vue/src/assets/iconfont.js
  vue/src/charts/ChartsDashboard.vue
  vue/src/charts/README.md
  vue/src/charts/components/ChartContainer.vue
  vue/src/charts/components/ChartsContainer.vue
  vue/src/charts/components/PannelButton.vue
  vue/src/charts/package/LineChart.vue
  vue/src/components/menu/SLMenuItem.vue
  vue/src/i18n/en-US/common.json
  vue/src/i18n/zh-CN/common.json
Labels: enhancement

#399 Refactor/audio chart
  swanlab/server/controller/project.py
  vue/src/charts/modules/AudioModule.vue
  vue/src/charts/package/AudioChart.vue
  vue/src/charts/package/ImageChart.vue
Labels: enhancement

#395 Feature/multi exp charts
  swanlab/server/controller/utils/charts.py
  vue/src/charts/components/LinChartTooltip.vue
  vue/src/charts/components/SlideBar.vue
  vue/src/charts/modules/AudioModule.vue
  vue/src/charts/package/AudioChart.vue
  vue/src/charts/package/ImageChart.vue
  vue/src/components/SLSlideBar.vue
  vue/src/store/modules/project.js
Labels: enhancement

#402 fix: remove event listener
  vue/src/views/home/components/ExprTable.vue
Labels: bug

#403 Feature/default step
  swanlab/server/controller/utils/charts.py
  vue/src/charts/components/LineChartLegend.vue
  vue/src/charts/components/PlayButton.vue
  vue/src/charts/components/SlideBar.vue
  vue/src/charts/modules/AudioModule.vue
  vue/src/charts/modules/TextModule.vue
  vue/src/charts/package/AudioChart.vue
  vue/src/charts/package/ImageChart.vue
  vue/src/charts/package/LineChart.vue
Labels: enhancement

#401 Fixbug/jupyter
  swanlab/log/console.py
Labels: bug

#407 ui: min height
  swanlab/data/modules/image.py
  vue/src/charts/package/ImageChart.vue
Labels: bug

#410 Update ImageChart.vue
  vue/src/charts/package/ImageChart.vue
Labels: UI/UX Enhancement

#415 Fixbug/stop during init
  .eslintrc-auto-import.json
  swanlab/server/controller/experiment.py
  vue/src/views/experiment/pages/environment/pages/EnvHardware.vue
  vue/src/views/experiment/pages/environment/pages/EnvRequirements.vue
Labels: bug

#422 Refactor/exp data
  .eslintrc-auto-import.json
  swanlab/data/run/exp.py
  swanlab/server/controller/experiment.py
  swanlab/server/controller/project.py
  swanlab/server/controller/utils/__init__.py
  swanlab/server/controller/utils/tag.py
  vue/src/charts/modules/ImageModule.vue
  vue/src/charts/package/ImageChart.vue
Labels: enhancement, good attempt

#423 Fixbug/swan consoler
  swanlab/log/console.py
  vue/src/views/experiment/pages/log/LogPage.vue
Labels: bug

#430 Fix/vue
  vue/src/App.vue
  vue/src/api/http.js
  vue/src/components/SLModal.vue
  vue/src/components/message/SLMessage.vue
  vue/src/components/message/SLMessages.vue
  vue/src/components/message/index.js
  vue/src/layouts/main/MainLayout.vue
Labels: bug, enhancement
