Repository SwanHubX/SwanLab, pull requests merged in 2025-06, with the labels that each got.

#1004 docs: readme changelog 0.6.0
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
  swanlab/package.json
Labels: 📚 documentation

#1007 docs: readme echarts
  README.md
  README_EN.md
  readme_files/echarts.png
Labels: 📚 documentation

#1016 update SwanLabTracker for accelerate
  swanlab/integration/accelerate.py
Labels: 🐛 bug, 💪 enhancement

#1020 feat: support DCU monitor
  swanlab/data/run/metadata/hardware/__init__.py
  swanlab/data/run/metadata/hardware/dcu/hygon.py
  swanlab/data/run/metadata/hardware/gpu/moorethreads.py
Labels: 🐛 bug, 💪 enhancement

#1017 fix: metax type
  swanlab/data/run/metadata/hardware/gpu/metax.py
Labels: 💪 enhancement

#1012 feat: allow get npu power
  swanlab/data/run/metadata/hardware/npu/ascend.py
Labels: 💪 enhancement

#1028 Create __main__.py
  swanlab/__main__.py
Labels: 🐛 bug

#1034 feat: leveldb
  swanlab/cli/commands/ sync/__init__.py
  swanlab/log/backup/__init__.py
  swanlab/log/backup/datastore.py
  swanlab/log/backup/handler.py
  swanlab/log/backup/models.py
  test/unit/log/backup/test_datastore.py
Labels: 📚 documentation, 💪 enhancement

#1041 fix/cambricon monitor
  README.md
  README_EN.md
  swanlab/data/run/metadata/hardware/dcu/hygon.py
  swanlab/data/run/metadata/hardware/mlu/cambricon.py
Labels: 🐛 bug

#1039 feat: mmengine config
  swanlab/data/run/config.py
Labels: 💪 enhancement

#1048 refactor: change backup mode to offline
  requirements.txt
  swanlab/data/callbacker/backup.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
  swanlab/data/utils.py
  swanlab/env.py
  test/unit/data/test_sdk.py
  tutils/__init__.py
Labels: 💪 enhancement

#1053 feat: update xgboost integration
  swanlab/integration/xgboost.py
Labels: 💪 enhancement

#1047 Feature/sync
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
  requirements.txt
  swanlab/__init__.py
  swanlab/api/http.py
  swanlab/api/upload/__init__.py
  swanlab/api/upload/model.py
  swanlab/cli/commands/__init__.py
  swanlab/cli/commands/sync/__init__.py
  swanlab/cli/main.py
  swanlab/data/callbacker/cloud.py
  swanlab/data/callbacker/local.py
  swanlab/data/callbacker/offline.py
  swanlab/data/callbacker/utils.py
  swanlab/data/cloud/__init__.py
  swanlab/data/namer.py
  swanlab/data/run/callback.py
  swanlab/data/run/helper.py
  swanlab/data/run/main.py
  swanlab/data/run/metadata/__init__.py
  swanlab/data/sdk.py
  swanlab/data/utils.py
  swanlab/env.py
  swanlab/log/backup/__init__.py
  swanlab/log/backup/datastore.py
  swanlab/log/backup/handler.py
  swanlab/log/backup/models.py
  swanlab/log/backup/writer.py
  swanlab/log/log.py
  swanlab/log/type.py
  swanlab/plugin/notification.py
  swanlab/plugin/writer.py
  swanlab/swanlab_settings.py
  swanlab/sync/__init__.py
  test/unit/data/callbacker/test_local.py
  test/unit/data/run/test_config.py
  test/unit/data/run/test_main.py
  test/unit/data/test_sdk.py
  test/unit/log/backup/test_datastore.py
  test/unit/log/backup/test_models.py
  test/unit/sync/test_sync.py
  tutils/__init__.py
Labels: 📚 documentation, 💪 enhancement

#859 将torch.profiler保存至本地
  swanlab/log/__init__.py
  swanlab/log/profiler.py
Labels: 💪 enhancement

#1073 fix: pip list freeze
  swanlab/data/run/metadata/requirements.py
Labels: 💪 enhancement

#1068 feat:add-table
  swanlab/data/modules/__init__.py
  swanlab/data/modules/custom_charts/__init__.py
  swanlab/data/modules/custom_charts/echarts.py
  swanlab/data/modules/custom_charts/table.py
  swanlab/data/modules/wrapper.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
  test/metrics/echarts/README.md
  test/metrics/echarts/table.py
  test/unit/data/modules/echarts/test_table.py
  test/unit/data/test_sdk.py
Labels: 💪 enhancement

#1086 docs: reamde 0.6.3
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
  readme_files/swanlab-and-user.png
Labels: 📚 documentation

#1088 fix: #1084
  swanlab/converter/wb/wb_converter.py
Labels: 🐛 bug

#1095 Fix/some bugs
  requirements.txt
  swanlab/data/callbacker/cloud.py
  swanlab/data/callbacker/local.py
  swanlab/data/modules/custom_charts/__init__.py
  swanlab/data/run/callback.py
  swanlab/data/run/metadata/requirements.py
  swanlab/data/utils.py
  swanlab/log/backup/handler.py
Labels: 🐛 bug

#1100 Feature/core
  .github/workflows/test-core.yml
  core/.golangci.yml
  core/LICENSE
  core/README.md
  core/cmd/core/core.go
  core/go.mod
  core/go.sum
  core/internal/api/api.go
  core/internal/api/parse.go
  core/internal/api/parse_test.go
  core/internal/service/collector.go
  core/pkg/pb/collector_service.pb.go
  core/pkg/pb/collector_service_grpc.pb.go
  core/pkg/pb/common.pb.go
  core/pkg/pb/record.pb.go
  requirements-dev.txt
  script/build_proto.py
  swanlab/proto/common/v1/common.proto
  swanlab/proto/common/v1/common_pb2.py
  swanlab/proto/common/v1/common_pb2.pyi
  swanlab/proto/core/collector/v1/collector_service.proto
  swanlab/proto/core/collector/v1/collector_service_pb2.py
  swanlab/proto/core/collector/v1/collector_service_pb2.pyi
  swanlab/proto/core/collector/v1/collector_service_pb2_grpc.py
  swanlab/proto/core/health/v1/health_service.proto
  swanlab/proto/record/v1/record.proto
  swanlab/proto/record/v1/record_pb2.py
  swanlab/proto/record/v1/record_pb2.pyi
Labels: 💪 enhancement

#1102 Refactor/core python
  swanlab/api/__init__.py
  swanlab/api/openapi/base.py
  swanlab/cli/commands/sync/__init__.py
  swanlab/core_python/__init__.py
  swanlab/core_python/client/__init__.py
  swanlab/core_python/client/cos.py
  swanlab/core_python/client/model.py
  swanlab/core_python/uploader/__init__.py
  swanlab/core_python/uploader/model.py
  swanlab/core_python/uploader/thread/__init__.py
  swanlab/core_python/uploader/thread/log_collector.py
  swanlab/core_python/uploader/thread/start_thread.py
  swanlab/core_python/uploader/thread/task_types.py
  swanlab/core_python/uploader/thread/utils.py
  swanlab/core_python/uploader/upload.py
  swanlab/data/callbacker/cloud.py
  swanlab/data/run/main.py
  swanlab/data/run/metadata/cooperation/__init__.py
  swanlab/data/run/metadata/runtime.py
  swanlab/data/run/public.py
  swanlab/data/sdk.py
  swanlab/log/backup/models.py
  swanlab/sync/__init__.py
  test/unit/_/test_setup.py
  test/unit/core_python/test_client.py
  test/unit/core_python/uploader/test_model.py
  test/unit/data/run/metadata/test_runtime.py
  test/unit/data/test_sdk.py
  tutils/setup.py
Labels: 💪 enhancement

#1105 docs: fix readme typo
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation

#1107 fix: requests version
  requirements.txt
Labels: 🐛 bug

#1108 feat: LogdirFileWriter plugin
  swanlab/plugin/__init___.py
  swanlab/plugin/writer.py
Labels: 💪 enhancement

#1114 feat: integration ray
  swanlab/integration/ray.py
Labels: 💪 enhancement

#1110 feat: reinit
  swanlab/data/sdk.py
  test/unit/data/test_sdk.py
Labels: 💪 enhancement

#1116 docs: readme accelerate
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation

#1126 Refactor/data-code
  requirements.txt
  swanlab/__init__.py
  swanlab/cli/commands/sync/__init__.py
  swanlab/core_python/__init__.py
  swanlab/core_python/auth/providers/api_key.py
  swanlab/core_python/client/__init__.py
  swanlab/data/__init__.py
  swanlab/data/callbacker/__init__.py
  swanlab/data/callbacker/callback.py
  swanlab/data/callbacker/cloud.py
  swanlab/data/callbacker/disabled.py
  swanlab/data/callbacker/local.py
  swanlab/data/callbacker/offline.py
  swanlab/data/callbacker/utils.py
  swanlab/data/porter/__init__.py
  swanlab/data/porter/datastore.py
  swanlab/data/run/__init__.py
  swanlab/data/run/callback.py
  swanlab/data/run/exp.py
  swanlab/data/run/helper.py
  swanlab/data/run/main.py
  swanlab/data/run/public.py
  swanlab/data/sdk.py
  swanlab/data/store.py
  swanlab/data/utils.py
  swanlab/log/backup/__init__.py
  swanlab/log/backup/handler.py
  swanlab/log/backup/writer.py
  swanlab/log/type.py
  swanlab/proto/v0.py
  swanlab/proto/v1.py
  swanlab/sync/__init__.py
  swanlab/toolkit/__init__.py
  test/unit/_/test_setup.py
  test/unit/conftest.py
  test/unit/core_python/test_client.py
  test/unit/core_python/uploader/test_model.py
  test/unit/data/backup/test_datastore.py
  test/unit/data/callbacker/test_local.py
  test/unit/data/run/metadata/test_runtime.py
  test/unit/data/run/test_config.py
  test/unit/data/run/test_main.py
  test/unit/data/test_sdk.py
  test/unit/proto/v0/test_models.py
  test/unit/sync/v0/test_sync.py
  tutils/setup.py
Labels: 🐛 bug, 💪 enhancement

#1135 docs(readme): add areal
  README.md
  README_EN.md
Labels: 📚 documentation
