Repository SwanHubX/SwanLab, pull requests merged in 2025-09, with the labels that each got.

#1249 docs(readme): integration mlx lm
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation

#1257 chore: restrict pydantic version
  requirements.txt
Labels: 🐛 bug

#1258 chore: opt retry params
  swanlab/api/base.py
  swanlab/core_python/__init__.py
  swanlab/core_python/auth/providers/api_key.py
  swanlab/core_python/client/__init__.py
  swanlab/core_python/session.py
  test/unit/core_python/test_client.py
  test/unit/core_python/test_session.py
Labels: 🐛 bug

#1271 docs(readme): unified architecture
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation

#1276 fix: change pydantic version constraint in requirements
  requirements.txt
Labels: 🐛 bug

#1274 Add verify command to check login status
  swanlab/cli/commands/__init__.py
  swanlab/cli/commands/auth/__init__.py
  swanlab/cli/commands/auth/verify.py
  swanlab/cli/main.py
  test/unit/cli/test_cli_verify.py
Labels: 💪 enhancement

#1277 feat: add interrupt handling for experiment termination
  swanlab/core_python/client/__init__.py
  swanlab/data/callbacker/callback.py
  swanlab/data/callbacker/cloud.py
  swanlab/data/run/main.py
  swanlab/data/store.py
Labels: 💪 enhancement
