Repository SwanHubX/SwanLab, pull requests merged in 2025-05, with the labels that each got.

#959 chore: revert upload column (#953)
  swanlab/api/upload/__init__.py
  swanlab/swanlab_settings.py
Labels: 🐛 bug

#961 feat(openapi): list workspaces
  docs/开放API.md
  swanlab/__init__.py
  swanlab/api/openapi/__init__.py
  swanlab/api/openapi/base.py
  swanlab/api/openapi/experiment.py
  swanlab/api/openapi/group.py
  swanlab/api/openapi/main.py
  swanlab/api/openapi/project.py
  test/unit/api/openapi/test_group.py
Labels: 💪 enhancement

#968 docs: readme update
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation

#973 feat: add intergation `paddlenlp`
  swanlab/integration/paddlenlp.py
  test/integration/paddlenlp/train.py
Labels: 💪 enhancement

#974 chore: revert upload column again
  swanlab/api/upload/__init__.py
  swanlab/data/cloud/task_types.py
  swanlab/swanlab_settings.py
Labels: 💪 enhancement

#981 docs: readme 0.5.8
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation

#982 feat: add tags to an experiment during SwanLab initialization
  requirements.txt
  swanlab/api/http.py
  swanlab/data/callbacker/cloud.py
  swanlab/data/formatter.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
Labels: 💪 enhancement

#983 feat: security mask
  swanlab/api/http.py
  swanlab/data/run/metadata/runtime.py
  swanlab/swanlab_settings.py
  test/unit/data/run/metadata/test_runtime.py
Labels: 💪 enhancement

#985 fix: resend request when experiment does not exist
  swanlab/api/http.py
  swanlab/api/upload/__init__.py
Labels: 🐛 bug

#987 feat: support moorethreads collector
  README.md
  README_EN.md
  swanlab/data/run/metadata/hardware/__init__.py
  swanlab/data/run/metadata/hardware/gpu/moorethread.py
Labels: 💪 enhancement

#990 feat: add integration tags
  swanlab/integration/accelerate.py
  swanlab/integration/fastai.py
  swanlab/integration/paddlenlp.py
  swanlab/integration/pytorch_lightning.py
  swanlab/integration/sb3.py
  swanlab/integration/torchtune.py
  swanlab/integration/transformers.py
  swanlab/integration/ultralytics.py
Labels: 💪 enhancement

#994 feat: compat self host api
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
  swanlab/api/http.py
Labels: 🐛 bug, 💪 enhancement

#995 chore: some misc
  swanlab/api/http.py
Labels: 🐛 bug

#980 feat: get_requirements support pixi
  swanlab/data/run/metadata/conda.py
  swanlab/data/run/metadata/requirements.py
  test/unit/data/run/metadata/test_conda.py
  test/unit/data/run/metadata/test_requirements.py
Labels: 💪 enhancement

#986 feat: echarts chart
  .gitignore
  requirements.txt
  swanlab/__init__.py
  swanlab/data/__init__.py
  swanlab/data/modules/__init__.py
  swanlab/data/modules/echarts/__init__.py
  swanlab/data/modules/wrapper.py
  swanlab/data/run/exp.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
  test/metrics/assets/molecule.example.pdb
  test/metrics/echarts/README.md
  test/metrics/echarts/bar/bar.py
  test/metrics/echarts/bar/bar2.py
  test/metrics/echarts/bar3d.py
  test/metrics/echarts/boxplot.py
  test/metrics/echarts/calendar_test.py
  test/metrics/echarts/candlestick.py
  test/metrics/echarts/dataset.py
  test/metrics/echarts/effectscatter.py
  test/metrics/echarts/funnel.py
  test/metrics/echarts/gauge.py
  test/metrics/echarts/geo.py
  test/metrics/echarts/graph.py
  test/metrics/echarts/graphgl.py
  test/metrics/echarts/graphic.py
  test/metrics/echarts/grid.py
  test/metrics/echarts/heatmap.py
  test/metrics/echarts/image.py
  test/metrics/echarts/line/line.py
  test/metrics/echarts/line/line2.py
  test/metrics/echarts/line3d.py
  test/metrics/echarts/liquid.py
  test/metrics/echarts/map.py
  test/metrics/echarts/map3d.py
  test/metrics/echarts/mapglobe.py
  test/metrics/echarts/overlap.py
  test/metrics/echarts/page.py
  test/metrics/echarts/parallel.py
  test/metrics/echarts/pictorialbar.py
  test/metrics/echarts/pie.py
  test/metrics/echarts/polar.py
  test/metrics/echarts/radar.py
  test/metrics/echarts/sankey.py
  test/metrics/echarts/scatter.py
  test/metrics/echarts/scatter3d.py
  test/metrics/echarts/sunburst.py
  test/metrics/echarts/surface3d.py
  test/metrics/echarts/tab.py
  test/metrics/echarts/table.py
  test/metrics/echarts/theme.py
  test/metrics/echarts/themeriver.py
  test/metrics/echarts/timeline.py
  test/metrics/echarts/tree.py
  test/metrics/echarts/treemap.py
  test/metrics/echarts/wordcloud.py
  test/unit/data/modules/echarts/test_eharts.py
  test/unit/data/run/test_main.py
Labels: 💪 enhancement

#1000 fix: only all and stderr can upload error info
  swanlab/data/run/main.py
Labels: 🐛 bug
