Repository SwanHubX/SwanLab, pull requests merged in 2025-07, with the labels that each got.

#1140 Fix host string handling in save_key and add tests
  swanlab/package.py
  test/unit/test_package.py
Labels: 🐛 bug

#1146 Ensure netrc file is properly flushed and synced
  swanlab/data/porter/__init__.py
  swanlab/data/porter/datastore.py
  swanlab/package.py
Labels: 🐛 bug, 💪 enhancement

#1141 Featrure/resume
  swanlab/core_python/client/__init__.py
  swanlab/core_python/client/model.py
  swanlab/core_python/uploader/upload.py
  swanlab/data/callbacker/callback.py
  swanlab/data/callbacker/cloud.py
  swanlab/data/callbacker/disabled.py
  swanlab/data/callbacker/local.py
  swanlab/data/callbacker/offline.py
  swanlab/data/formatter.py
  swanlab/data/modules/wrapper.py
  swanlab/data/namer.py
  swanlab/data/porter/__init__.py
  swanlab/data/run/config.py
  swanlab/data/run/exp.py
  swanlab/data/run/key.py
  swanlab/data/run/main.py
  swanlab/data/run/metadata/hardware/__init__.py
  swanlab/data/run/metadata/hardware/utils.py
  swanlab/data/sdk.py
  swanlab/data/store.py
  swanlab/env.py
  swanlab/log/log.py
  test/resume/allow.py
  test/resume/must.py
  test/unit/core_python/test_client.py
  test/unit/data/callbacker/test_cloud.py
  test/unit/data/run/test_config.py
  test/unit/data/run/test_key.py
  test/unit/data/run/test_main.py
  test/unit/data/test_formatter.py
  test/unit/data/test_namer.py
  test/unit/data/test_sdk.py
  tutils/setup.py
Labels: 💪 enhancement

#1152 Remove LocalRunCallback import and update callback imports
  swanlab/data/callbacker/__init__.py
  swanlab/data/utils.py
Labels: 💪 enhancement

#1143 docs: readme resume
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation

#1157 Fix resume parameter handling and add env var tests
  swanlab/data/sdk.py
  test/unit/data/test_sdk.py
Labels: 🐛 bug, 💪 enhancement

#1159 feat: improve sync series
  swanlab/sync/tensorboard.py
  swanlab/sync/wandb.py
  test/sync_mlflow.py
  test/sync_tensorboardX.py
  test/sync_tensorboard_torch.py
  test/sync_wandb.py
Labels: 💪 enhancement

#1161 feat: match online mode
  swanlab/data/sdk.py
  test/unit/data/test_sdk.py
Labels: 🪿tiny

#1172 Refactor section assignment logic in SwanLabKey
  swanlab/data/run/key.py
Labels: 💪 enhancement

#1174 Fix error key usage in SwanLabKey class
  swanlab/data/run/key.py
  test/unit/data/run/test_key.py
Labels: 🐛 bug

#765 feat: swanlab.Video
  requirements-media.txt
  swanlab/__init__.py
  swanlab/data/modules/__init__.py
  swanlab/data/modules/image/__init__.py
  swanlab/data/modules/video/__init__.py
  test/metrics/video.py
  test/unit/data/modules/image/test_gif.py
  test/unit/data/modules/video/test_video.py
Labels: 💪 enhancement

#1181 docs: readme changelog 0.6.7
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
  readme_files/swanlab-logo-single-dark.svg
  readme_files/swanlab-logo-single.svg
Labels: 📚 documentation

#1193 docs(readme): add lerobot guide in readme
  README.md
  README_EN.md
Labels: 📚 documentation

#1195 fix: Windows 系统下，与 accelerate 一起使用时，local 模式因默认 gkb 编码导致报错
  swanlab/proto/v0.py
Labels: 🐛 bug

#1208 fix: sync resume folder
  swanlab/data/run/key.py
  test/resume/must.py
  test/unit/data/run/test_key.py
Labels: 🐛 bug

#1212 docs(readme): 0.6.8
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation
