Repository SwanHubX/SwanLab, pull requests merged in 2025-03, with the labels that each got.

#843 feat: cloud only and subcontracting
  .github/workflows/test-when-pr.yml
  docs/插件化设计.md
  docs/登录认证.md
  pyproject.toml
  requirements-dashboard.txt
  requirements.txt
  swanlab/api/upload/__init__.py
  swanlab/cli/commands/dashboard/watch.py
  swanlab/data/callbacker/cloud.py
  swanlab/data/callbacker/local.py
  swanlab/data/callbacker/utils.py
  swanlab/data/formatter.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
Labels: 💪 enhancement

#821 feat: s3 sdk
  requirements.txt
  swanlab/api/cos.py
Labels: 🐛 bug, 💪 enhancement

#849 fix: console recorder not enabled in cloud mode
  swanlab/data/callbacker/cloud.py
  swanlab/log/__init__.py
  swanlab/log/console.py
  swanlab/log/log.py
Labels: 💪 enhancement

#848 feat: conda env
  requirements.txt
  swanlab/api/upload/__init__.py
  swanlab/api/upload/model.py
  swanlab/data/callback_cloud.py
  swanlab/data/run/main.py
  swanlab/data/run/metadata/__init__.py
  swanlab/data/run/metadata/conda.py
  test/unit/api/upload/test_model.py
  test/unit/data/run/metadata/hardware/test_conda.py
Labels: 🐛 bug, 💪 enhancement

#853 fix: wandb conver
  swanlab/converter/wb/wb_converter.py
Labels: 🐛 bug

#854 fix: convert wandb metadata
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
  swanlab/converter/wb/wb_converter.py
Labels: 🐛 bug

#857 fix: hf integration
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
  swanlab/integration/huggingface.py
Labels: 🐛 bug

#862 feat: support self-hosted (#843)
  .github/workflows/test-when-pr.yml
  docs/插件化设计.md
  docs/登录认证.md
  pyproject.toml
  requirements-dashboard.txt
  requirements.txt
  swanlab/api/auth/login.py
  swanlab/api/cos.py
  swanlab/api/upload/__init__.py
  swanlab/cli/commands/dashboard/watch.py
  swanlab/data/callbacker/cloud.py
  swanlab/data/callbacker/local.py
  swanlab/data/callbacker/utils.py
  swanlab/data/formatter.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
  swanlab/log/__init__.py
  swanlab/log/console.py
  swanlab/log/log.py
  swanlab/package.py
  test/unit/api/auth/test_login.py
  test/unit/data/test_sdk.py
  test/unit/test_package.py
Labels: 💪 enhancement

#870 feat: add args for callback
  requirements-dashboard.txt
  requirements.txt
  swanlab/data/callbacker/cloud.py
  swanlab/data/callbacker/local.py
  swanlab/data/run/helper.py
  swanlab/data/run/main.py
Labels: 💪 enhancement

#871 feat: add register callbacks command
  swanlab/__init__.py
  swanlab/data/__init__.py
  swanlab/data/sdk.py
  swanlab/data/utils.py
  test/unit/data/test_sdk.py
Labels: 💪 enhancement

#866 feat: custom callbacks
  requirements-dashboard.txt
  swanlab/plugin/__init___.py
  swanlab/plugin/notification.py
  swanlab/plugin/writer.py
Labels: 💪 enhancement

#874 feat: 'GPU Memory Allocated(MB)' for system monitor
  swanlab/data/run/metadata/hardware/gpu/nvidia.py
  test/unit/data/run/metadata/hardware/gpu/test_nvidia.py
Labels: 💪 enhancement

#873 fix: del print
  requirements-dashboard.txt
  swanlab/plugin/writer.py
Labels: 🐛 bug

#875 docs: self hosted
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation

#881 fix: transformers integration add step
  swanlab/integration/transformers.py
Labels: 🐛 bug

#884 feat: disk io and network sent receive
  swanlab/data/run/metadata/hardware/__init__.py
  swanlab/data/run/metadata/hardware/cpu.py
  swanlab/data/run/metadata/hardware/disk.py
  swanlab/data/run/metadata/hardware/memory.py
  swanlab/data/run/metadata/hardware/network.py
  swanlab/data/run/metadata/hardware/soc/apple.py
  swanlab/data/run/metadata/hardware/type.py
  swanlab/data/run/metadata/hardware/utils.py
  test/unit/data/run/metadata/hardware/test_disk.py
  test/unit/data/run/metadata/hardware/test_network.py
  test/unit/data/run/metadata/hardware/test_utils.py
Labels: 💪 enhancement

#890 swanlab package version
  swanlab/package.json
  test/unit/data/run/metadata/hardware/test_disk.py
Labels: 💪 enhancement

#891 docs: readme add plugin and repo
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation

#892 fix: concurrent error
  swanlab/api/cos.py
Labels: 🐛 bug

#844 Feat/3d point cloud
  swanlab/__init__.py
  swanlab/api/http.py
  swanlab/data/__init__.py
  swanlab/data/modules/__init__.py
  swanlab/data/modules/object3d/__init__.py
  swanlab/data/modules/object3d/model3d.py
  swanlab/data/modules/object3d/object3d.py
  swanlab/data/modules/object3d/point_cloud.py
  swanlab/data/namer.py
  swanlab/data/run/main.py
  swanlab/data/run/metadata/hardware/type.py
  test/metrics/assets/.gitignore
  test/metrics/object_3d.py
  test/unit/data/modules/object3d/conftest.py
  test/unit/data/modules/object3d/test_model3d.py
  test/unit/data/modules/object3d/test_object3d.py
  test/unit/data/modules/object3d/test_point_cloud.py
  test/unit/data/run/test_namer.py
  test/unit/data/test_namer.py
Labels: 💪 enhancement

#899 fix: object 3d error type infer
  swanlab/data/modules/object3d/object3d.py
Labels: 🐛 bug

#898 docs: readme 0.5.3
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
  readme_files/swanlab-docker.png
Labels: 📚 documentation

#900 feat: convert improve
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
  swanlab/converter/mlf/mlf_converter.py
  swanlab/converter/tfb/tfb_converter.py
  swanlab/converter/wb/wb_converter.py
Labels: 💪 enhancement

#901 feat: env add gpu nvidia architecture and cudacores
  swanlab/data/run/metadata/hardware/gpu/nvidia.py
Labels: 💪 enhancement

#906 feat: ascend cann version
  swanlab/data/run/metadata/hardware/npu/ascend.py
  swanlab/integration/accelerate.py
  swanlab/integration/fastai.py
  swanlab/integration/huggingface.py
  swanlab/integration/mmengine.py
  swanlab/integration/pytorch_lightning.py
  swanlab/integration/sb3.py
  swanlab/integration/torchtune.py
  swanlab/integration/transformers.py
  swanlab/integration/ultralytics.py
  swanlab/integration/xgboost.py
Labels: 💪 enhancement

#903 feat: swanlab.Settings -- A Global Feature Switch Management Module
  requirements.txt
  swanlab/__init__.py
  swanlab/data/__init__.py
  swanlab/data/run/main.py
  swanlab/data/sdk.py
  swanlab/swanlab_settings.py
  test/unit/log/test_log.py
  test/unit/test_swanlab_settings.py
Labels: 💪 enhancement

#904 Fix: Change Dict to dict in _TYPE_HANDLERS type hints
  swanlab/data/modules/object3d/object3d.py
Labels: 🐛 bug

#911 fix(docs): en redirection
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation

#912 feat: gpu time of memory
  swanlab/data/run/metadata/hardware/gpu/nvidia.py
  test/unit/data/run/metadata/hardware/gpu/test_nvidia.py
Labels: 💪 enhancement

#914 refactor: settings
  swanlab/data/callbacker/cloud.py
  swanlab/data/cloud/log_collector.py
  swanlab/data/run/main.py
  swanlab/data/run/metadata/__init__.py
  swanlab/data/run/metadata/hardware/__init__.py
  swanlab/data/run/metadata/hardware/disk.py
  swanlab/data/run/metadata/runtime.py
  swanlab/data/sdk.py
  swanlab/log/console.py
  swanlab/swanlab_settings.py
  test/unit/log/test_log.py
  test/unit/test_swanlab_settings.py
Labels: 💪 enhancement

#918 fix snyc wandb finish
  swanlab/sync/wandb.py
Labels: 🐛 bug

#921 feat: new env
  swanlab/api/http.py
  swanlab/data/sdk.py
  swanlab/data/utils.py
  swanlab/env.py
  test/unit/data/test_sdk.py
Labels: 💪 enhancement

#919 docs: readme 0.5.4
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation
