Repository SwanHubX/SwanLab, pull requests merged in 2025-01, with the labels that each got.

#772 docs: readme 2.0
  README.md
  readme_files/charts-1.gif
  readme_files/example-catsdogs.png
  readme_files/example-lstm.png
  readme_files/example-qwen2.png
  readme_files/example-yolo.png
  readme_files/experiments-table.png
  readme_files/get-started.png
  readme_files/integrations.png
  readme_files/introduction.png
  readme_files/mutilmedia-chart.gif
  readme_files/overview-2.png
  readme_files/readme-mnist.png
  readme_files/star-us.png
  readme_files/swanlab-head-image.png
  readme_files/swanlab-logo-single.svg
  readme_files/swanlab-logo.svg
  readme_files/swanlab-overview.png
Labels: 📚 documentation

#774 docs: sync lang
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation

#775 feat: integration mark
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
  swanlab/integration/accelerate.py
  swanlab/integration/fastai.py
  swanlab/integration/lightgbm.py
  swanlab/integration/mmengine.py
  swanlab/integration/pytorch_lightning.py
  swanlab/integration/sb3.py
  swanlab/integration/torchtune.py
  swanlab/integration/transformers.py
  swanlab/integration/ultralytics.py
  swanlab/integration/xgboost.py
Labels: 📚 documentation

#778 feat: dynamic catch collect task error
  swanlab/data/run/metadata/hardware/gpu/nvidia.py
  swanlab/data/run/metadata/hardware/type.py
  swanlab/data/sdk.py
  test/unit/data/run/metadata/hardware/test_type.py
Labels: 🐛 bug, 💪 enhancement

#779 Revert "fix: temporary domain (#756)"
  swanlab/env.py
Labels: 🦠 invalid

#781 chore: add setuptools for build
  requirements.txt
Labels: 🐛 bug

#783 feat: add choices for swanlab.init
  swanlab/api/auth/login.py
  swanlab/data/callback_cloud.py
  swanlab/data/sdk.py
  swanlab/env.py
  swanlab/package.py
  test/unit/data/test_sdk.py
  test/unit/test_env.py
  test/unit/test_package.py
Labels: 💪 enhancement

#787 feat: delete task runtime
  requirements.txt
  swanlab/cli/commands/__init__.py
  swanlab/cli/commands/launcher/__init__.py
  swanlab/cli/commands/launcher/parser/__init__.py
  swanlab/cli/commands/launcher/parser/model.py
  swanlab/cli/commands/launcher/parser/v1/__init__.py
  swanlab/cli/commands/launcher/parser/v1/folder.py
  swanlab/cli/commands/task/__init__.py
  swanlab/cli/commands/task/list.py
  swanlab/cli/commands/task/search.py
  swanlab/cli/commands/task/stop.py
  swanlab/cli/commands/task/utils.py
  swanlab/cli/commands/uploader/__init__.py
  swanlab/cli/main.py
  swanlab/cli/utils.py
  swanlab/data/callback_cloud.py
  swanlab/data/run/main.py
  swanlab/data/run/public.py
  swanlab/env.py
  test/unit/cli/test_cli_launch.py
  test/unit/cli/test_cli_task.py
  test/unit/cli/test_cli_utils.py
  test/unit/data/test_sdk.py
Labels: 💪 enhancement

#785 feat: sync wandb
  swanlab/__init__.py
  swanlab/sync/__init__.py
  swanlab/sync/wandb.py
  test/wandb_sync.py
Labels: 💪 enhancement

#790 docs: changelog 0.4.3
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation

#794 feat: sync wandb add params
  swanlab/sync/wandb.py
Labels: 💪 enhancement

#796 feat: sync tensorboard(x)
  swanlab/__init__.py
  swanlab/sync/__init__.py
  swanlab/sync/tensorboard.py
  test/sync_tensorboardX.py
  test/sync_tensorboard_torch.py
  test/sync_wandb.py
Labels: 💪 enhancement

#798 feat: only one api key
  swanlab/package.py
  test/unit/test_package.py
Labels: 💪 enhancement

#799 feat: sync enhancement
  swanlab/sync/tensorboard.py
  swanlab/sync/wandb.py
  test/sync_tensorboardX.py
  test/sync_tensorboard_torch.py
  test/sync_wandb.py
Labels: 💪 enhancement

#800 docs: readme darkmode
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
  readme_files/swanlab-logo-single-dark.svg
  readme_files/swanlab-overview-new.png
Labels: 📚 documentation

#803 chore: add api and web host to http obj
  swanlab/api/__init__.py
  swanlab/api/auth/login.py
  swanlab/api/http.py
  swanlab/api/info.py
  swanlab/cli/commands/auth/login.py
  swanlab/cli/commands/auth/logout.py
  swanlab/data/callback_cloud.py
  swanlab/data/run/metadata/cooperation/__init__.py
  swanlab/data/run/public.py
  swanlab/data/sdk.py
  swanlab/package.py
  test/unit/api/auth/test_login.py
  test/unit/test_package.py
  tutils/setup.py
Labels: 💪 enhancement
