Repository SwanHubX/SwanLab, pull requests merged in 2025-04, with the labels that each got.

#922 feat: cambricon mlu temperature and power
  swanlab/data/run/metadata/hardware/__init__.py
  swanlab/data/run/metadata/hardware/mlu/cambricon.py
Labels: 💪 enhancement

#923 fix: cambricon power
  swanlab/data/run/metadata/hardware/mlu/cambricon.py
Labels: 🐛 bug

#925 fix: move cambricon from npu to mlu
  swanlab/data/run/metadata/hardware/__init__.py
  swanlab/data/run/metadata/hardware/mlu/cambricon.py
Labels: 🐛 bug

#928 fix: memory type
  swanlab/data/run/metadata/hardware/gpu/nvidia.py
  swanlab/data/run/metadata/hardware/memory.py
  swanlab/data/run/metadata/hardware/mlu/cambricon.py
  swanlab/data/run/metadata/hardware/npu/ascend.py
  swanlab/data/run/metadata/hardware/soc/apple.py
Labels: 💪 enhancement

#920 [Feature] Molecule Meida Object3D Support.
  requirements-media.txt
  requirements.txt
  swanlab/__init__.py
  swanlab/data/__init__.py
  swanlab/data/modules/__init__.py
  swanlab/data/modules/object3d/__init__.py
  swanlab/data/modules/object3d/molecule.py
  swanlab/data/modules/object3d/object3d.py
  test/metrics/assets/molecule.example.pdb
  test/metrics/molecule.py
  test/metrics/object_3d.spatiallm.example.py
  test/unit/data/modules/object3d/test_molecule.py
Labels: 💪 enhancement

#933 docs: demo video
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation

#934 docs: add evalscope
  README.md
  README_EN.md
Labels: 📚 documentation

#935 feat: trace id for backend
  swanlab/api/http.py
Labels: 🐛 bug, 💪 enhancement

#936 docs: readme changelog
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
Labels: 📚 documentation

#932 feat:add func of get uv requirements
  swanlab/data/run/metadata/__init__.py
  swanlab/data/run/metadata/requirements.py
  test/unit/data/run/metadata/hardware/test_uv.py
Labels: 💪 enhancement

#944 fix: pynvml version conflict
  swanlab/data/run/metadata/hardware/gpu/nvidia.py
Labels: 🐛 bug

#947 feat: os pretty name
  swanlab/data/run/metadata/runtime.py
Labels: 💪 enhancement

#953 feat/multi-columns update
  swanlab/api/http.py
  swanlab/api/upload/__init__.py
  swanlab/swanlab_settings.py
Labels: 💪 enhancement

#954 fix: object3d import error
  swanlab/data/modules/object3d/object3d.py
  swanlab/data/modules/object3d/point_cloud.py
Labels: 🐛 bug

#955 chore: change (max columns)/req
  swanlab/api/upload/__init__.py
Labels: 💪 enhancement

#940 feat: hardware monitor add kunlunxin xpu
  README.md
  README_EN.md
  README_JP.md
  README_RU.md
  swanlab/data/run/metadata/hardware/__init__.py
  swanlab/data/run/metadata/hardware/xpu/kunlunxin.py
Labels: 💪 enhancement

#956 fix: can not get pip list
  swanlab/data/run/metadata/requirements.py
  test/unit/data/run/metadata/test_requirements.py
Labels: 💪 enhancement
